---
# The variables file used by the playbooks in the homelab_lxc group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

# Docker Networks

# Note bridge networks are external by default unless 'internal: true' is set

# # Docker Socker Proxy External is an external network which services that connect to Docker APIs on external hosts need to be on
# # Services include Homepage, Uptime Kuma and What's Up Docker?
# docker_socket_proxy_external_network_name: docker-socket-proxy-external

# Reverse Proxy Network is an external network that all applications hosted behind the reverse proxy (in this case Traefik) need to be on
reverse_proxy_network_name: reverse-proxy

# Socker Proxy External is an external network which services that connect to Docker APIs on external hosts need to be on
# Services include Homepage, Uptime Kuma and What's Up Docker?
socket_proxy_external_network_name: socket-proxy-external

# Containerised service facts

# Docker Volume Backup facts
# renovate: datasource=docker depName=offen/docker-volume-backup
docker_volume_backup_image: offen/docker-volume-backup:v2.48.2
# Hawser facts
# renovate: datasource=docker depName=ghcr.io/finsys/hawser
hawser_image: ghcr.io/finsys/hawser:0.2.46
# Postgres facts
# renovate: datasource=docker depName=postgres
postgres_image: postgres:16-alpine
# Redis facts
# renovate: datasource=docker depName=redis
redis_image: redis:8.8-alpine
# SearXNG facts
# renovate: datasource=docker depName=searxng/searxng
searxng_image: searxng/searxng:2026.6.28-8605230eb
# Socket Proxy facts
# renovate: datasource=docker depName=wollomatic/socket-proxy
socket_proxy_image: wollomatic/socket-proxy:1.12.2
# Tinyauth facts
# renovate: datasource=docker depName=ghcr.io/steveiliop56/tinyauth
tinyauth_image: ghcr.io/steveiliop56/tinyauth:v5.0.7
# Traefik facts
# renovate: datasource=docker depName=traefik
traefik_image: traefik:3.7.5
traefik_entrypoint_insecure_name: web
traefik_entrypoint_secure_name: "{{ traefik_entrypoint_insecure_name | default('web') }}secure"

socket_proxy_ports:
  traefik: 2375
  hawser: 2376
  uptimekuma: 2377
  wud: 2378
  homepage: 2379
  authentik_worker: 2380

# Global definition of backup directory on hosts
local_backups_dir: /root/backups/

default_host_volumes:
  # Local paths to mount into the container
  # local path:container path
  - /etc/localtime:/etc/localtime:ro
  # - /etc/timezone:/etc/timezone:ro

docker_host_volume:
  # Local paths to mount into the container
  # local path:container path
  - /var/run/docker.sock:/var/run/docker.sock
