---

# The variables file used by the playbooks in the homelab_lxc group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

# Docker Networks
# Note bridge networks are external by default unless internal: true is set
# Docker Socket Proxy is used to connect services to the Docker API via the
# docker-socket-proxy service
# Read-Only access to the Docker Socket Proxy
# Used by most services (Traefik, Homepage and Uptime Kuma)
docker_socket_proxy_network_name: docker-socket-proxy
docker_socket_proxy_network_interal: false
# Read-Write access to the Docker Socket Proxy
# Used by services that need to stop/start containers (Portainer Agent, Docker Volume Backup)
docker_socket_proxy_rw_network_name: docker-socket-proxy-rw
docker_socket_proxy_rw_network_interal: true
# Monitoring is an internal network that is not exposed outside the host
monitoring_network_name: monitoring
monitoring_network_internal: true
# Web is an external network that is exposed outside the host
web_network_name: web
web_network_internal: false

# Docker manager service networks
beszel_network_name: beszel
dozzle_network_name: dozzle
portainer_network_name: portainer

# Containerised service facts
# Docker Volume Backup facts
docker_volume_backup_image: offen/docker-volume-backup:v2.44.0
# Dozzle Agent facts
dozzle_agent_image: amir20/dozzle:v8.13.12
# Node Exporter facts
node_exporter_image: prom/node-exporter:v1.9.1
# Portainer Agent facts
portainer_agent_image: portainer/agent:2.33.1-alpine
# Prometheus facts
prometheus_image: prom/prometheus:v3.5.0
# Tinyauth facts
tinyauth_image: ghcr.io/steveiliop56/tinyauth:v3.6.2
# Traefik facts
traefik_image: traefik:3.5.1


# Global definition of backup directory on hosts
local_backups_dir: /root/backups

default_host_volumes:
  # Local paths to mount into the container
  # local path:container path
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro

docker_host_volume:
  # Local paths to mount into the container
  # local path:container path
  - /var/run/docker.sock:/var/run/docker.sock
