---

# The variables file used by the playbooks in the homelab_lxc group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

# Docker Networks

# Note bridge networks are external by default unless 'internal: true' is set

# Docker Socker Proxy External is an external network which services that connect to Docker APIs on external hosts need to be on
# Services include Homepage, Uptime Kuma and What's Up Docker?
docker_socket_proxy_external_network_name: docker-socket-proxy-external

# Reverse Proxy Network is an external network that all applications hosted behind the reverse proxy (in this case Traefik) need to be on
reverse_proxy_network_name: reverse-proxy

# Docker manager service networks, are all external to connect to agents
beszel_network_name: beszel
dozzle_network_name: dozzle
portainer_network_name: portainer

# Containerised service facts

# Docker Socket Proxy service facts
# renovate: datasource=docker depName=ghcr.io/tecnativa/docker-socket-proxy
docker_socket_proxy_image: ghcr.io/tecnativa/docker-socket-proxy:v0.4.1
# Docker Volume Backup facts
# renovate: datasource=docker depName=offen/docker-volume-backup
docker_volume_backup_image: offen/docker-volume-backup:v2.44.0
# Dozzle Agent facts
# renovate: datasource=docker depName=amir20/dozzle
dozzle_agent_image: amir20/dozzle:v8.13.14
# Node Exporter facts
# renovate: datasource=docker depName=prom/node-exporter
node_exporter_image: prom/node-exporter:v1.9.1
# Portainer Agent facts
# renovate: datasource=docker depName=portainer/agent
portainer_agent_image: portainer/agent:2.33.1-alpine
# Prometheus facts
# renovate: datasource=docker depName=prom/prometheus
prometheus_image: prom/prometheus:v3.5.0
# Tinyauth facts
# renovate: datasource=docker depName=ghcr.io/steveiliop56/tinyauth
tinyauth_image: ghcr.io/steveiliop56/tinyauth:v3.6.2
# Traefik facts
# renovate: datasource=docker depName=traefik
traefik_image: traefik:3.5.2

# Global definition of backup directory on hosts
local_backups_dir: /root/backups

default_host_volumes:
  # Local paths to mount into the container
  # local path:container path
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro

docker_host_volume:
  # Local paths to mount into the container
  # local path:container path
  - /var/run/docker.sock:/var/run/docker.sock

# Name of entrypoint for Reverse Proxy - Traefik
traefik_entrypoint_insecure_name: web
traefik_entrypoint_secure_name: "{{ traefik_entrypoint_insecure_name | default('web') }}secure"
