---

# The variables file used by the playbooks in the homelab_lxc group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

# Docker Network names
# TODO: Define as an array
docker_socket_proxy_network_name: docker-socket-proxy
monitoring_network_name: monitoring
web_network_name: web

# Containerised service facts
# docker-volume-backup facts
docker_volume_backup_image_name: offen/docker-volume-backup
docker_volume_backup_image_tag: v2.43.1
docker_volume_backup_service_name: "docker-volume-backup"
# Duplicati facts
duplicati_image_name: lscr.io/linuxserver/duplicati
duplicati_image_tag: v2.1.0.3_beta_2025-01-22-ls232
duplicati_service_name: duplicati
duplicati_service_port: 8200
duplicati_volume_config: config
duplicati_volume_backups: backups
duplicati_volume_source: source
