---

# The variables file used by the playbooks in the homelab_lxc group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

# Docker Networks
# Docker Socket Proxy is used to connect services to the Docker API via the
# docker-socket-proxy service
docker_socket_proxy_network_name: docker-socket-proxy
docker_socket_proxy_network_interal: true
# Monitoring is an internal network that is not exposed outside the host
monitoring_network_name: monitoring
monitoring_network_internal: true
# Web is an external network that is exposed outside the host
web_network_name: web
web_network_internal: false

# Containerised service facts
# Docker Volume Backup facts
docker_volume_backup_image: offen/docker-volume-backup:v2.43.4
docker_volume_backup_service_name: docker-volume-backup
docker_volume_backup_local_archive_dir: /root/backups
# Dozzle Agent facts
dozzle_agent_image: amir20/dozzle:v8.13.1
dozzle_agent_service_name: dozzle-agent
dozzle_agent_service_port: 7007
# Node Exporter facts
node_exporter_image: prom/node-exporter:v1.9.1
node_exporter_service_name: node-exporter
node_exporter_service_port: 9100
node_exporter_service_protocol: http
# Portainer Agent facts
portainer_agent_image: portainer/agent:2.31.1-alpine
portainer_agent_service_name: portainer_agent
portainer_agent_service_port: 9001
# Prometheus facts
prometheus_image: prom/prometheus:v3.3.1
prometheus_service_name: prometheus
prometheus_service_port: 9090
prometheus_volume_name: prometheus
# Tinyauth facts
tinyauth_image: ghcr.io/steveiliop56/tinyauth:v3.4.1
tinyauth_service_name: tinyauth
tinyauth_service_port: 3000
# Traefik facts
traefik_image: traefik:3.4.1
traefik_service_name: traefik
traefik_service_port: 80
traefik_service_port_http: 80
traefik_service_port_secure: 443
traefik_provider: docker
traefik_volume_letsencrypt_name: letsencrypt

# Global definition of backup directory on hosts
local_backups_dir: /root/backups
