---
roles:
  - name: geerlingguy.docker
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-docker
    version: 8.0.0

  - name: geerlingguy.pip
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-pip
    version: 3.1.2

collections:
  # required to use Docker
  - name: community.docker
    version: 5.0.6
    type: galaxy

  - name: ansible.utils
    version: 6.0.1
    type: galaxy
