---
roles:
  # To install Docker
  # https://github.com/geerlingguy/ansible-role-docker
  - name: geerlingguy.docker
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-docker
    version: 8.0.0

collections:
  # To use Docker
  # https://docs.ansible.com/projects/ansible/latest/collections/community/docker/index.html
  - name: community.docker
    version: 5.2.0
    type: galaxy

  # To configure timezone using 'community.general.timezone'
  # https://docs.ansible.com/projects/ansible/latest/collections/community/general/index.html
  - name: community.general
    version: 12.6.0
    type: galaxy
