---

####### Traefik Manager SECTION

- name: deploy-traefik-manager | Set Traefik Manager facts
  ansible.builtin.set_fact:
    traefik_manager_image: "{{ traefik_manager_image | default('ghcr.io/chr0nzz/traefik-manager:latest') }}"
    traefik_manager_service_name: "{{ traefik_manager_service_name | default('traefik-manager') }}"
    traefik_manager_service_port: "{{ traefik_manager_service_port | default(5000) }}"

- name: deploy-traefik-manager | Set Traefik Manager network facts
  ansible.builtin.set_fact:
    traefik_manager_network_name: "{{ traefik_manager_network_name | default(reverse_proxy_network_name) }}"

- name: deploy-traefik-manager | Set Traefik Manager volume facts
  ansible.builtin.set_fact:
    traefik_manager_volume_config_name: "{{ traefik_manager_volume_config_name | default(traefik_manager_service_name + '_config') }}"
    traefik_manager_volume_backups_name: "{{ traefik_manager_volume_backups_name | default(traefik_manager_service_name + '_backups') }}"
    traefik_config_file: "{{ traefik_config_file | default('/root/traefik/dynamic.yml') }}"

- name: deploy-traefik-manager | Set Traefik Manager aggregated facts
  ansible.builtin.set_fact:
    traefik_manager_fqdn: "{{ traefik_manager_service_name }}.{{ ansible_facts['hostname'] }}.{{ homelab.certificate_domain | default('localdomain') }}"

- name: deploy-traefik-manager | Set Traefik Manager service facts
  ansible.builtin.set_fact:
    traefik_manager_networks:
      # Reverse Proxy  network is used to expose applications via Traefik
      - { name: "{{ reverse_proxy_network_name | default('reverse-proxy') }}" }
    traefik_manager_ports:
      # Published ports to expose outside the container
      # host port:container port
      # use high ports inside the container so
      # we don't need to be root to bind the ports
      - "{{ traefik_manager_service_port }}:5000"
    traefik_manager_volumes:
      # Local paths to mount into the container
      # local path:container path
      - "{{ traefik_manager_volume_config_name }}:/app/config"
      - "{{ traefik_manager_volume_backups_name }}:/app/backups"
      - "{{ traefik_config_file }}:/app/config/dynamic.yml:rw"

- name: deploy-traefik-manager | Log Traefik Manager configuration
  ansible.builtin.debug:
    msg:
      - "Traefik Manager image: {{ traefik_manager_image }}"
      - "Traefik Manager service name: {{ traefik_manager_service_name }}"
      - "Traefik Manager FQDN: {{ traefik_manager_fqdn }}"
      - "Traefik Manager networks: {{ traefik_manager_networks | default(omit) }}"
      - "Traefik Manager ports: {{ traefik_manager_ports | default(omit) }}"
      - "Traefik Manager volumes: {{ traefik_manager_volumes | default(omit) }}"

- name: deploy-traefik-manager | Create Traefik Manager container labels
  ansible.builtin.set_fact:
    traefik_manager_container_labels: "{{ traefik_manager_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # ---------------------------------------------------------------
    # Traefik Manager configuration labels to override default static configuration
    - { "key": "traefik.enable", "value": "true" }
    - {
      "key": "traefik.http.routers.{{ traefik_manager_service_name }}.entrypoints",
      "value": "{{ traefik_entrypoint_secure_name }}",
    }
    - {
      "key": "traefik.http.routers.{{ traefik_manager_service_name }}.rule",
      "value": "Host(`{{ traefik_manager_fqdn }}`)",
    }
    # ---------------------------------------------------------------
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/chr0nzz/traefik-manager/releases/tag/v${major}.${minor}.${patch}",
    }

- name: deploy-traefik-manager | Create Traefik Manager networks
  when: traefik_manager_networks is defined
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal | default(false) }}"
    state: present
  loop: "{{ traefik_manager_networks }}"

- name: deploy-traefik-manager | Create Traefik Manager volumes
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ traefik_manager_volume_config_name }}"
    - "{{ traefik_manager_volume_backups_name }}"

- name: deploy-traefik-manager | Pull Traefik Manager image
  community.docker.docker_image:
    name: "{{ traefik_manager_image }}"
    source: pull

- name: deploy-traefik-manager | Deploy Traefik Manager
  community.docker.docker_container:
    name: "{{ traefik_manager_service_name }}"
    image: "{{ traefik_manager_image }}"
    detach: true
    env:
      COOKIE_SECURE: "false"
    labels: "{{ traefik_manager_container_labels | default(omit) }}"
    networks: "{{ traefik_manager_networks | ansible.utils.remove_keys(target=['internal']) | default(omit) }}"
    restart: true
    restart_policy: unless-stopped
    security_opts:
      - "no-new-privileges:true"
    state: started
    volumes: "{{ default_host_volumes + traefik_manager_volumes | default(omit) }}"
  register: traefik_manager_container_state

- name: deploy-traefik-manager | Wait for Traefik Manager to accept connections
  when: false # Temporarily disable as no DNS entry for Traefik Manager on all hosts
  ansible.builtin.wait_for:
    host: "{{ traefik_manager_fqdn }}"
    port: "{{ traefik_manager_service_port }}"
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 30
  register: traefik_manager_running
  retries: 10
  until: traefik_manager_running is success
