---
- name: deploy-dozzle-agent | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

####### DOZZLE AGENT SECTION

# https://dozzle.dev/guide/agent

- name: deploy-dozzle-agent | Set Dozzle Agent facts
  ansible.builtin.set_fact:
    dozzle_agent_image: "{{ dozzle_agent_image | default('amir20/dozzle:latest') }}"
    dozzle_agent_service_name: "{{ dozzle_agent_service_name | default('dozzle-agent') }}"
    dozzle_agent_service_port: "{{ dozzle_agent_service_port | default(7007) }}"

- name: deploy-dozzle-agent | Set Dozzle Agent service facts
  ansible.builtin.set_fact:
    dozzle_agent_networks:
      - name: "{{ dozzle_network_name | default('dozzle') }}"
    dozzle_agent_ports:
      - "{{ dozzle_agent_service_port }}:7007"
    dozzle_agent_volumes: []

- name: deploy-dozzle-agent | Create Dozzle Agent container labels
  ansible.builtin.set_fact:
    dozzle_agent_container_labels: "{{ dozzle_agent_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/amir20/dozzle/releases/tag/v${major}.${minor}.${patch}",
    }

- name: deploy-dozzle-agent | Create Dozzle network  # noqa: syntax-check[unknown-module]
  community.docker.docker_network:
    name: "{{ dozzle_network_name }}"
    driver: "bridge"
    internal: false

- name: deploy-dozzle-agent | Pull Dozzle Agent image
  community.docker.docker_image:
    name: "{{ dozzle_agent_image }}"
    source: pull

# docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 amir20/dozzle:latest
- name: deploy-dozzle-agent | Deploy Dozzle Agent
  community.docker.docker_container:
    name: "{{ dozzle_agent_service_name }}"
    image: "{{ dozzle_agent_image }}"
    command: agent
    detach: true
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    labels: "{{ dozzle_agent_container_labels | default(omit) }}"
    networks_cli_compatible: true
    networks: "{{ dozzle_agent_networks | default(omit) }}"
    published_ports: "{{ dozzle_agent_ports | default(omit) }}"
    restart: true
    restart_policy: unless-stopped
    state: started
    volumes: "{{ default_host_volumes + docker_host_volume + dozzle_agent_volumes | default(omit) }}"
  register: dozzle_agent_container_state
