---
- name: deploy-mysql | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

# - name: deploy-mysql | Ensure required MySQL variables are set
#   ansible.builtin.assert:
#     that:
#       - mysql_root_password is defined
#       - mysql_database_name is defined
#       - mysql_user_name is defined
#       - mysql_user_password is defined
#     fail_msg: "One or more required MySQL variables are not defined! Please define them in your inventory or group_vars/host_vars."

####### MYSQL SECTION

# http://www.mysql.com/
# https://github.com/mysql/mysql-server
# https://hub.docker.com/_/mysql

- name: deploy-mysql | Set MySQL facts
  ansible.builtin.set_fact:
    mysql_image: "{{ mysql_image | default('mysql:latest') }}"
    mysql_image_tag: "{{ mysql_image_tag | default('latest') }}"
    mysql_service_name: "{{ mysql_service_name | default('mysql') }}"
    mysql_service_port: "{{ mysql_service_port | default(3306) }}"

- name: deploy-mysql | Set MySQL network facts
  ansible.builtin.set_fact:
    mysql_network_name: "{{ mysql_network_name | default(mysql_service_name) }}"

- name: deploy-mysql | Set MySQL volume facts
  ansible.builtin.set_fact:
    mysql_volume_name: "{{ mysql_volume_name | default(mysql_service_name) }}"

- name: deploy-mysql | Set MySQL aggregated facts
  ansible.builtin.set_fact:
    mysql_fqdn: "{{ mysql_service_name }}.{{ ansible_hostname }}.{{ homelab.certificate_domain | default('localdomain') }}"

- name: deploy-mysql | Set MySQL service facts
  ansible.builtin.set_fact:
    mysql_args: "{{ mysql_args | default(omit) }}"
    mysql_command: "{{ mysql_command | default(omit) }}"
    mysql_env: "{{ mysql_env | default(omit) }}"
    mysql_env_file: "{{ mysql_env_file | default(omit) }}"
    mysql_healthcheck: "{{ mysql_healthcheck | default(omit) }}"
    mysql_networks:
      - { name: "{{ mysql_network_name }}", internal: true }
    mysql_ports:
      # Published ports to expose outside the container
      # host port:container port
      - "{{ mysql_service_port }}:3306"
    mysql_volumes:
      # Local paths to mount into the container
      # local path:container path
      - "{{ mysql_volume_name }}:/var/lib/mysql"

- name: deploy-mysql | Log MySQL configuration
  ansible.builtin.debug:
    msg:
      - "MySQL image: {{ mysql_image }}"
      - "MySQL service name: {{ mysql_service_name }}"
      - "MySQL FQDN: {{ mysql_fqdn }}"
      - "MySQL command: {{ mysql_command | default(omit) }}"
      - "MySQL env: {{ mysql_env | default(omit) }}"
      - "MySQL env_file: {{ mysql_env_file | default(omit) }}"
      - "MySQL healthcheck: {{ mysql_healthcheck | default(omit) }}"
      - "MySQL networks: {{ mysql_networks | default(omit) }}"
      - "MySQL ports: {{ mysql_ports | default(omit) }}"
      - "MySQL volumes: {{ mysql_volumes | default(omit) }}"

- name: deploy-mysql | Create MySQL container labels
  ansible.builtin.set_fact:
    mysql_container_labels: "{{ mysql_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # ---------------------------------------------------------------
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/mysql/mysql/releases/tag/mysql-${major}.${minor}.${patch}",
    }

# Create required Docker networks
- name: deploy-mysql | Create MySQL networks
  when: mysql_networks is defined
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal | default(false) }}"
    state: present
  loop: "{{ mysql_networks }}"

# Create required Docker volumes
- name: deploy-mysql | Create MySQL volumes
  when: mysql_volume_name is defined
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ mysql_volume_name }}"

- name: deploy-mysql | Check if MySQL is running
  community.docker.docker_container_info:
    name: "{{ mysql_service_name }}"
  register: mysql_state

- name: deploy-mysql | Remove MySQL container if changing version
  when:
    - mysql_state.exists
    - (mysql_image | split(':') | last) != (mysql_state.container.Config.Image | split(':') | last)
  block:

    - name: deploy-mysql | Stop and remove existing MySQL container
      community.docker.docker_container:
        name: "{{ mysql_service_name }}"
        state: absent

    - name: deploy-mysql | Set update MySQL
      ansible.builtin.set_fact:
        mysql_update: true

- name: deploy-mysql | Deploy MySQL if not running
  when:
    - not mysql_state.exists or (mysql_update | default(false))
  block:

    - name: deploy-mysql | Pull MySQL image
      community.docker.docker_image:
        name: "{{ mysql_image }}"
        source: pull

    - name: deploy-mysql | Deploy MySQL
      community.docker.docker_container:
        name: "{{ mysql_service_name }}"
        image: "{{ mysql_image }}"
        command: "{{ mysql_command | default(omit) }}"
        detach: true
        env: "{{ mysql_env | default(omit) }}"
        # env_file: "{{ mysql_env_file | default(omit) }}"
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 5s
        labels: "{{ mysql_container_labels | default(omit) }}"
        networks_cli_compatible: true
        networks: "{{ mysql_networks | ansible.utils.remove_keys(target=['internal']) | default(omit) }}"
        restart: true
        restart_policy: unless-stopped
        state: started
        volumes: "{{ default_host_volumes + mysql_volumes | default(omit) }}"
      register: mysql_container_state
