---
- name: deploy-emqx | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

# https://hub.docker.com/r/emqx/emqx
# https://github.com/iotblue/emqx-docker
# https://www.emqx.com/en/try?product=broker (EMQX Open Source)
# https://dev.to/emqtech/running-emqx-mqtt-broker-on-docker-bonus-clustering-and-persistence-4mo3

- name: deploy-emqx | Set EMQX facts
  ansible.builtin.set_fact:
    emqx_image: "{{ emqx_image | default('emqx/emqx:latest') }}"
    emqx_image_tag: "{{ emqx_image_tag | default('latest') }}"
    emqx_service_name: "{{ emqx_service_name | default('emqx') }}"
    emqx_service_port_api: "{{ emqx_service_port_api | default(18083) }}"
    emqx_service_port_mqtt: "{{ emqx_service_port_mqtt | default(1883) }}"
    emqx_data_volume_name: "{{ emqx_data_volume_name | default('data') }}"
    emqx_log_volume_name: "{{ emqx_log_volume_name | default('log') }}"

- name: deploy-emqx | Set EMQX aggregated facts
  ansible.builtin.set_fact:
    emqx_fqdn: "{{ emqx_service_name }}.{{ ansible_hostname }}.{{ homelab.lan_domain | default('localdomain') }}"

- name: deploy-emqx | Get status of Prometheus Docker container
  community.docker.docker_container_info:
    name: "{{ prometheus_service_name | default('prometheus') }}"
  register: prometheus_container_status
  ignore_errors: true

- name: deploy-emqx | Configure Prometheus when deployed
  when: prometheus_container_status.exists
  block:
    - name: deploy-emqx | Set Prometheus aggregated facts
      ansible.builtin.set_fact:
        prometheus_fqdn: "{{ prometheus_service_name }}.{{ ansible_hostname }}.{{ homelab.lan_domain | default('localdomain') }}"

    - name: deploy-emqx | Create Prometheus configuration directory
      ansible.builtin.file:
        path: /root/prometheus
        mode: "644"
        state: directory
      register: prometheus_configuration_creation

    - name: deploy-emqx | Create Prometheus configuration file for EMQX
      ansible.builtin.template:
        src: templates/prometheus/prometheus-emqx.yml.j2
        dest: /root/prometheus/prometheus.yml
        mode: "644"
      register: prometheus_configuration_creation

    - name: deploy-emqx | Redeploy Prometheus with new configuration # noqa: syntax-check[unknown-module]
      community.docker.docker_container:
        name: "{{ prometheus_service_name | default('prometheus') }}"
        restart: true
        state: started
      register: prometheus_container_state

- name: deploy-emqx | Set EMQX service facts
  ansible.builtin.set_fact:
    emqx_networks:
      - name: "{{ broker_network_name | default('broker') }}"
      - name: "{{ web_network_name | default('web') }}"
    emqx_ports:
      # - "{{ emqx_service_port_api | default(18083) }}:18083"
      - "{{ emqx_service_port_mqtt | default(1883) }}:1883"
      - 8083:8083 # websocket
      # - 4369:4369
      # - 5369:5369
      # - 6000-6100:6000-6100
    emqx_volumes:
      - "{{ emqx_data_volume_name }}:/opt/emqx/data"
      - "{{ emqx_log_volume_name }}:/opt/emqx/log"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

- name: deploy-emqx | Create EMQX container labels
  ansible.builtin.set_fact:
    emqx_container_labels: "{{ emqx_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # Traefik labels
    - { "key": "traefik.enable", "value": "true" }
    - { "key": "traefik.docker.network", "value": "{{ web_network_name }}" }
    - {
      "key": "traefik.http.routers.{{ emqx_service_name }}.entrypoints",
      "value": "websecure",
    }
    - {
      "key": "traefik.http.routers.{{ emqx_service_name }}.rule",
      "value": "Host(`{{ emqx_fqdn }}`)",
    }
    - {
      "key": "traefik.http.routers.{{ emqx_service_name }}.service",
      "value": "{{ emqx_service_name }}",
    }
    - {
      "key": "traefik.http.routers.{{ emqx_service_name }}.tls",
      "value": "true",
    }
    - {
      "key": "traefik.http.services.{{ emqx_service_name }}.loadbalancer.server.port",
      "value": "{{ emqx_service_port_api | quote }}",
    }
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/emqx/emqx/releases/tag/v${major}.${minor}.${patch}",
    }
    # Homepage labels
    - { "key": "homepage.group", "value": "Monitoring" }
    - { "key": "homepage.name", "value": "Broker" }
    - { "key": "homepage.description", "value": "MQTT Broker" }
    - { "key": "homepage.icon", "value": "emqx.png" }
    - { "key": "homepage.href", "value": "https://{{ emqx_fqdn }}/" }
    - { "key": "homepage.siteMonitor", "value": "https://{{ emqx_fqdn }}/" }

- name: deploy-emqx | Check if EMQX is running
  community.docker.docker_container_info:
    name: "{{ emqx_service_name }}"
  register: emqx_state

- name: deploy-emqx | Remove EMQX container if changing version
  when:
    - emqx_state.exists
    - (emqx_image | split(':') | last) != (emqx_state.container.Config.Image | split(':') | last)
  block:
    - name: deploy-emqx | Stop and remove existing EMQX container
      community.docker.docker_container:
        name: "{{ emqx_service_name }}"
        state: absent

    - name: deploy-emqx | Set update EMQX
      ansible.builtin.set_fact:
        emqx_update: true

- name: deploy-emqx | Deploy EMQX if not running
  when:
    - not emqx_state.exists or (emqx_update | default(false))
  block:
    - name: deploy-emqx | Pull EMQX image
      community.docker.docker_image:
        name: "{{ emqx_image }}"
        source: pull

    - name: deploy-emqx | Deploy EMQX
      community.docker.docker_container:
        name: "{{ emqx_service_name }}"
        image: "{{ emqx_image }}"
        detach: true
        env:
          EMQX_ALLOW_ANONYMOUS: "true"
          EMQX_DASHBOARD__DEFAULT_PASSWORD: "{{ emqx.admin_password | default('dummy') }}"
          EMQX_LISTENER__TCP__EXTERNAL: "{{ emqx_service_port_mqtt | default(1883) | quote }}"
          EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_prometheus"
          EMQX_NAME: "{{ emqx_service_name | default('emqx') }}"
          EMQX_HOST: "{{ emqx_fqdn }}"
          WAIT_FOR_ERLANG: "60"
        labels: "{{ emqx_container_labels }}"
        networks_cli_compatible: true
        networks: "{{ emqx_networks }}"
        published_ports: "{{ emqx_ports }}"
        restart: true
        restart_policy: unless-stopped
        state: started
        volumes: "{{ emqx_volumes }}"
      register: emqx_container_state

    - name: deploy-emqx | Wait for EMQX to accept connections
      ansible.builtin.wait_for:
        host: "{{ emqx_fqdn }}"
        port: 80
        connect_timeout: 1
        delay: 10
        state: started
        timeout: 30
      register: emqx_running
      until: emqx_running is success
      retries: 10
