---
- name: deploy-docker-socket-proxy | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

# TODO: think about better ways of managing this
- name: deploy-docker-socket-proxy | Set Docker Socket Proxy configuration facts
  ansible.builtin.set_fact:
    docker_socket_proxy_configure_for_docker_volume_backup: "{{ docker_socket_proxy_configure_for_docker_volume_backup | default(false) }}"
    # docker_socket_proxy_publish_ports: "{{ docker_socket_proxy_publish_ports | default(false) }}"

####### DOCKER-SOCKET-PROXY SECTION

# https://github.com/Tecnativa/docker-socket-proxy
# https://docs.linuxserver.io/images/docker-socket-proxy/

# The default settings are as follows:
  # ALLOW_RESTARTS=0 \
  # ALLOW_STOP=0 \
  # ALLOW_START=0 \
  # AUTH=0 \
  # BUILD=0 \
  # COMMIT=0 \
  # CONFIGS=0 \
  # CONTAINERS=0 \
  # DISABLE_IPV6=0 \
  # DISTRIBUTION=0 \
  # EVENTS=1 \
  # EXEC=0 \
  # GRPC=0 \
  # IMAGES=0 \
  # INFO=0 \
  # LOG_LEVEL=info \
  # NETWORKS=0 \
  # NODES=0 \
  # PING=1 \
  # PLUGINS=0 \
  # POST=0 \
  # SECRETS=0 \
  # SERVICES=0 \
  # SESSION=0 \
  # SOCKET_PATH=/var/run/docker.sock \
  # SWARM=0 \
  # SYSTEM=0 \
  # TASKS=0 \
  # VERSION=1 \
  # VOLUMES=0
# Only the changed parameters need to be passed as environment variables to the container.

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy facts
  ansible.builtin.set_fact:
    docker_socket_proxy_image: "{{ docker_socket_proxy_image | default('ghcr.io/tecnativa/docker-socket-proxy:latest') }}"
    docker_socket_proxy_service_name: "{{ docker_socket_proxy_service_name | default('docker-socket-proxy') }}"
    docker_socket_proxy_service_port: "{{ docker_socket_proxy_service_port | default(2375) }}"

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy network facts
  ansible.builtin.set_fact:
    docker_socket_proxy_network_name: "{{ docker_socket_proxy_network_name | default(docker_socket_proxy_service_name) }}"
    docker_socket_proxy_network_internal: "{{ docker_socket_proxy_network_internal | default(true) }}"

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy volume facts
  ansible.builtin.set_fact:
    docker_socket_proxy_volume_name: "{{ docker_socket_proxy_volume_name | default(docker_socket_proxy_service_name) }}"

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy aggregated facts
  ansible.builtin.set_fact:
    docker_socket_proxy_fqdn: "{{ docker_socket_proxy_service_name }}.{{ ansible_hostname }}.{{ homelab.certificate_domain | default('localdomain') }}"

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy service facts
  ansible.builtin.set_fact:
    docker_socket_proxy_networks:
      - { name: "{{ docker_socket_proxy_network_name }}", internal: "{{ docker_socket_proxy_network_internal }}" }
    docker_socket_proxy_ports:
      - "{{ docker_socket_proxy_service_port }}:2375/tcp"
    docker_socket_proxy_volumes: []

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy env
  ansible.builtin.set_fact:
    docker_socket_proxy_env: "{{ docker_socket_proxy_env | default(omit) }}"

- name: deploy-docker-socket-proxy | Log Docker Socket Proxy configuration
  ansible.builtin.debug:
    msg:
      - "Docker Socket Proxy image: {{ docker_socket_proxy_image }}"
      - "Docker Socket Proxy service name: {{ docker_socket_proxy_service_name }}"
      - "Docker Socket Proxy FQDN: {{ docker_socket_proxy_fqdn }}"
      - "Docker Socket Proxy networks: {{ docker_socket_proxy_networks | default(omit) }}"
      - "Docker Socket Proxy ports: {{ docker_socket_proxy_ports | default(omit) }}"
      - "Docker Socket Proxy volumes: {{ docker_socket_proxy_volumes | default(omit) }}"
      - "Docker Socket Proxy env: {{ docker_socket_proxy_env | default(omit) }}"

- name: deploy-docker-socket-proxy | Create Docker Socket Proxy container labels
  ansible.builtin.set_fact:
    docker_socket_proxy_container_labels: "{{ docker_socket_proxy_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/Tecnativa/docker-socket-proxy/releases/tag/v${major}.${minor}.${patch}",
    }

- name: deploy-docker-socket-proxy | Create Docker Socket Proxy network
  when: docker_socket_proxy_networks is defined
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal }}"
    state: present
  loop: "{{ docker_socket_proxy_networks }}"

- name: deploy-docker-socket-proxy | Pull Docker Socket Proxy image
  community.docker.docker_image_pull:
    name: "{{ docker_socket_proxy_image }}"
    pull: always

- name: deploy-docker-socket-proxy | Deploy Docker Socket Proxy
  community.docker.docker_container:
    name: "{{ docker_socket_proxy_service_name }}"
    image: "{{ docker_socket_proxy_image }}"
    env: "{{ docker_socket_proxy_env | default(omit) }}"
      # # For details see https://github.com/Tecnativa/docker-socket-proxy
      # LOG_LEVEL: info # debug,info,notice,warning,err,crit,alert,emerg
      # ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # # 0 to revoke access.
      # # 1 to grant access.
      # # See https://offen.github.io/docker-volume-backup/how-tos/use-custom-docker-host.html for config details
      # # to support Docker Socket Proxy
      # ## Granted by Default
      # # These API sections are mostly harmless and almost required for any service that uses the API, so they are granted by default.
      # EVENTS: "1"
      # PING: "1"
      # VERSION: "1"
      # ## Revoked by Default
      # # Security critical
      # # These API sections are considered security-critical, and thus access is revoked by default. Maximum caution when enabling these.
      # AUTH: "0"
      # SECRETS: "0"
      # POST: "{{ \"1\" if docker_socket_proxy_configure_for_docker_volume_backup else \"0\" }}" # Allow access for Docker Volume Backup to stop containers
      # ## Not always needed
      # # You will possibly need to grant access to some of these API sections, which are not so extremely critical but can expose some information that your service does not need.
      # ALLOW_RESTARTS: "0" # (containers/id/stop|restart|kill)
      # ALLOW_START: "0" # (containers/id/start)
      # ALLOW_STOP: "0" # (containers/id/stop)
      # BUILD: "0"
      # COMMIT: "0"
      # CONFIGS: "0"
      # CONTAINERS: "1" # Allow listing and managing containers (Traefik, Homepage, WUD, Docker Volume Backup.)
      # DISTRIBUTION: "0"
      # EXEC: "{{ \"1\" if docker_socket_proxy_configure_for_docker_volume_backup else \"0\" }}" # Allow access for Docker Volume Backup to execute commands
      # GRPC: "0"
      # IMAGES: "0"
      # INFO: "{{ \"1\" if docker_socket_proxy_configure_for_docker_volume_backup else \"0\" }}" # Allow access for Docker Volume Backup to get swarm state
      # NETWORKS: "0" # Block listing newtworks
      # NODES: "{{ \"1\" if docker_socket_proxy_configure_for_docker_volume_backup else \"0\" }}" # Allow access for Docker Volume Backup to stop containers
      # PLUGINS: "0"
      # SERVICES: "0" # Block listing and managing services
      # SESSION: "0"
      # SWARM: "0"
      # SYSTEM: "0" # Block system-level API access
      # TASKS: "{{ \"1\" if docker_socket_proxy_configure_for_docker_volume_backup else \"0\" }}" # Allow access for Docker Volume Backup to stop containers
      # VOLUMES: "0" # Allow listing volumes
    labels: "{{ docker_socket_proxy_container_labels | default(omit) }}"
    networks: "{{ docker_socket_proxy_networks | ansible.utils.remove_keys(target=['internal']) | default(omit) }}"
    published_ports: "{{ docker_socket_proxy_ports if not docker_socket_proxy_network_internal else omit }}"
    recreate: true # Recreate to ensure env changes are used
    restart: true
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges=true
    state: started
    volumes: "{{ default_host_volumes + docker_host_volume + docker_socket_proxy_volumes | default(omit) }}"
  register: docker_socket_proxy_container_state

- name: deploy-docker-socket-proxy | Wait for Docker Socket Proxy to accept connections
  when: false # not use_docker_socket_proxy_rw not works, needs to be fixed
  ansible.builtin.wait_for:
    host: "{{ docker_socket_proxy_container_state['container']\
      ['NetworkSettings']\
      ['Networks']\
      [docker_monitoring_network_name]\
      ['IPAddress'] }}"
    port: "{{ docker_socket_proxy_service_port }}"
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 30
  register: docker_socket_proxy_running
  retries: 10
  until: docker_socket_proxy_running is success
