---

####### NEXTCLOUD ALL-IN-ONE SECTION

- name: deploy-nextcloud-aio-mastercontainer | Set Nextcloud All-in-One facts
  ansible.builtin.set_fact:
    nextcloud_aio_mastercontainer_image: "ghcr.io/nextcloud-releases/all-in-one:latest"
    nextcloud_aio_mastercontainer_service_name: "nextcloud-aio-mastercontainer"
    nextcloud_aio_mastercontainer_volume_name: "nextcloud-aio-mastercontainer"

- name: deploy-nextcloud-aio-mastercontainer | Set Nextcloud All-in-One service facts
  ansible.builtin.set_fact:
    # nextcloud_aio_mastercontainer_networks:
      # - { name: "{{ nextcloud_aio_mastercontainer_network_name }}" }
      # # Reverse Proxy  network is used to expose applications via Traefik
      # - { name: "{{ reverse_proxy_network_name | default('reverse-proxy') }}" }
    nextcloud_aio_mastercontainer_ports:
      # Published ports to expose outside the container
      # host port:container port
      # - 80:80
      - 8080:8080
      # - 8443:8443
    nextcloud_aio_mastercontainer_volumes:
      # Local paths to mount into the container
      # local path:container path
      - "{{ nextcloud_aio_mastercontainer_volume_name }}:/mnt/docker-aio-config"

- name: deploy-nextcloud-aio-mastercontainer | Log Nextcloud All-in-One configuration
  ansible.builtin.debug:
    msg:
      - "Nextcloud All-in-One image: {{ nextcloud_aio_mastercontainer_image }}"
      - "Nextcloud All-in-One service name: {{ nextcloud_aio_mastercontainer_service_name }}"
      - "Nextcloud All-in-One ports: {{ nextcloud_aio_mastercontainer_ports | default(omit) }}"
      - "Nextcloud All-in-One volumes: {{ nextcloud_aio_mastercontainer_volumes | default(omit) }}"

# - name: deploy-nextcloud-aio-mastercontainer | Create Nextcloud All-in-One container labels
#   ansible.builtin.set_fact:
#     nextcloud_aio_mastercontainer_container_labels: "{{ nextcloud_aio_mastercontainer_container_labels | default({}) | combine({item.key: item.value}) }}"
#   with_items:
#     # ---------------------------------------------------------------
#     # Traefik labels
#     - { "key": "traefik.enable", "value": "true" }
#     - {
#       "key": "traefik.http.routers.{{ nextcloud_aio_mastercontainer_service_name }}.entrypoints",
#       "value": "websecure",
#     }
#     - {
#       "key": "traefik.http.routers.{{ nextcloud_aio_mastercontainer_service_name }}.rule",
#       "value": "Host(`{{ nextcloud_aio_mastercontainer_fqdn }}`)",
#     }
#     # ---------------------------------------------------------------
#     # What's up Docker? labels
#     # - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
#     # - {
#     #   "key": "wud.link.template",
#     #   "value": "https://github.com/ollama/ollama/releases/tag/v${major}.${minor}.${patch}",
#     # }

- name: deploy-nextcloud-aio-mastercontainer | Create Nextcloud All-in-One volume
  when: nextcloud_aio_mastercontainer_volume_name is defined
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ nextcloud_aio_mastercontainer_volume_name }}"

- name: deploy-nextcloud-aio-mastercontainer | Check if Nextcloud All-in-One is running
  community.docker.docker_container_info:
    name: "{{ nextcloud_aio_mastercontainer_service_name }}"
  register: nextcloud_aio_mastercontainer_state

- name: deploy-nextcloud-aio-mastercontainer | Update Nextcloud All-in-One container if changing version
  when:
    - nextcloud_aio_mastercontainer_state.exists
    - (nextcloud_aio_mastercontainer_image | split(':') | last) != (nextcloud_aio_mastercontainer_state.container.Config.Image | split(':') | last)
  block:

    - name: deploy-nextcloud-aio-mastercontainer | Stop and remove existing Nextcloud All-in-One container
      community.docker.docker_container:
        name: "{{ nextcloud_aio_mastercontainer_service_name }}"
        state: absent

    - name: deploy-nextcloud-aio-mastercontainer | Set update Nextcloud All-in-One
      ansible.builtin.set_fact:
        nextcloud_aio_mastercontainer_update: true

- name: deploy-nextcloud-aio-mastercontainer | Deploy Nextcloud All-in-One if not running
  when: not nextcloud_aio_mastercontainer_state.exists or (nextcloud_aio_mastercontainer_update | default(false))
  block:

    - name: deploy-nextcloud-aio-mastercontainer | Pull Nextcloud All-in-One image
      community.docker.docker_image:
        name: "{{ nextcloud_aio_mastercontainer_image }}"
        source: pull

    # https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    - name: deploy-nextcloud-aio-mastercontainer | Deploy Nextcloud All-in-One
      community.docker.docker_container:
        name: "{{ nextcloud_aio_mastercontainer_service_name }}"
        image: "{{ nextcloud_aio_mastercontainer_image }}"
        detach: true
        env:
          NEXTCLOUD_DATADIR: "/mnt/nextcloud_data"
          APACHE_PORT: "11000"
          APACHE_IP_BINDING: "127.0.0.1"
          APACHE_ADDITIONAL_NETWORK: ""
          SKIP_DOMAIN_VALIDATION: "true" # "{{ true | quote }}"
        init: true
        labels: "{{ nextcloud_aio_mastercontainer_container_labels | default(omit) }}"
        networks_cli_compatible: true
        published_ports: "{{ nextcloud_aio_mastercontainer_ports }}"
        restart: true
        restart_policy: unless-stopped
        security_opts:
          - "no-new-privileges:true"
        state: started
        volumes: "{{ docker_host_volume + nextcloud_aio_mastercontainer_volumes | default(omit) }}"
      register: nextcloud_aio_mastercontainer_container_state

- name: deploy-nextcloud-aio-mastercontainer | Wait for Nextcloud All-in-One to accept connections
  when: false
  ansible.builtin.wait_for:
    host: "{{ nextcloud_aio_mastercontainer_fqdn }}"
    port: 80
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 30
  register: nextcloud_aio_mastercontainer_running
  retries: 10
  until: nextcloud_aio_mastercontainer_running is success
