---
####### HOMELABINFO SECTION

# https://homelabinfo.com/
# https://github.com/gregluffy/HomeLabInfo

- name: deploy-homelabinfo | Set HomeLabInfo facts
  ansible.builtin.set_fact:
    homelabinfo_image: "{{ homelabinfo_image | default('gfountopoulos/homelabinfo:latest') }}"
    homelabinfo_service_name: "{{ homelabinfo_service_name | default('homelabinfo') }}"
    homelabinfo_service_port: "{{ homelabinfo_service_port | default(8080) }}"

- name: deploy-homelabinfo | Set HomeLabInfo network facts
  ansible.builtin.set_fact:
    homelabinfo_network_name: "{{ homelabinfo_network_name | default(homelabinfo_service_name) }}"

- name: deploy-homelabinfo | Set HomeLabInfo volume facts
  ansible.builtin.set_fact:
    homelabinfo_volume_name: "{{ homelabinfo_volume_name | default(homelabinfo_service_name) }}"

- name: deploy-homelabinfo | Set HomeLabInfo aggregated facts
  ansible.builtin.set_fact:
    homelabinfo_fqdn: "{{ homelabinfo_service_name }}.{{ ansible_facts['hostname'] }}.{{ homelab.certificate_domain | default('localdomain') }}"

- name: deploy-homelabinfo | Set HomeLabInfo service facts
  ansible.builtin.set_fact:
    homelabinfo_networks:
      - { name: "{{ homelabinfo_network_name }}" }
      # Reverse Proxy  network is used to expose applications via Traefik
      - { name: "{{ reverse_proxy_network_name | default('reverse-proxy') }}" }
    homelabinfo_ports:
      # Published ports to expose outside the container
      # host port:container port
      - "{{ homelabinfo_service_port }}:8080"
    homelabinfo_volumes: []
      # Local paths to mount into the container
      # local path:container path

- name: deploy-homelabinfo | Log HomeLabInfo configuration
  ansible.builtin.debug:
    msg:
      - "HomeLabInfo image: {{ homelabinfo_image }}"
      - "HomeLabInfo service name: {{ homelabinfo_service_name }}"
      - "HomeLabInfo FQDN: {{ homelabinfo_fqdn }}"
      - "HomeLabInfo command: {{ homelabinfo_command | default(omit) }}"
      - "HomeLabInfo networks: {{ homelabinfo_networks | default(omit) }}"
      - "HomeLabInfo ports: {{ homelabinfo_ports | default(omit) }}"
      - "HomeLabInfo volumes: {{ homelabinfo_volumes | default(omit) }}"

- name: deploy-homelabinfo | Create HomeLabInfo container labels
  ansible.builtin.set_fact:
    homelabinfo_container_labels: "{{ homelabinfo_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # ---------------------------------------------------------------
    # Homepage labels
    - { "key": "homepage.group", "value": "Applications" }
    - { "key": "homepage.name", "value": "HomeLabInfo" }
    - { "key": "homepage.description", "value": "Description of HomeLabInfo" }
    - { "key": "homepage.icon", "value": "homelabinfo.png" }
    - { "key": "homepage.href", "value": "https://{{ homelabinfo_fqdn }}/" }
    - { "key": "homepage.siteMonitor", "value": "https://{{ homelabinfo_fqdn }}/" }
    # ---------------------------------------------------------------
    # Traefik labels
    - { "key": "traefik.enable", "value": "true" }
    - { "key": "traefik.http.routers.{{ homelabinfo_service_name }}.entrypoints", "value": "{{ traefik_entrypoint_secure_name }}" }
    - { "key": "traefik.http.routers.{{ homelabinfo_service_name }}.rule", "value": "Host(`{{ homelabinfo_fqdn }}`)" }
    # ---------------------------------------------------------------
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - { "key": "wud.link.template", "value": "https://github.com/alam00000/homelabinfo/releases/tag/v${major}.${minor}.${patch}" }

- name: deploy-homelabinfo | Create HomeLabInfo networks
  when: homelabinfo_networks is defined
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal | default(false) }}"
    state: present
  loop: "{{ homelabinfo_networks }}"

- name: deploy-homelabinfo | Create HomeLabInfo volumes
  when: homelabinfo_volume_cache_name is defined and homelabinfo_volume_config_name is defined and (homelabinfo_volumes | length > 0)
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ homelabinfo_volume_name }}"

- name: deploy-homelabinfo | Check if HomeLabInfo is running
  community.docker.docker_container_info:
    name: "{{ homelabinfo_service_name }}"
  register: homelabinfo_state

- name: deploy-homelabinfo | Remove HomeLabInfo container if changing version
  when:
    - homelabinfo_state.exists
    - (homelabinfo_image | split(':') | last) != (homelabinfo_state.container.Config.Image | split(':') | last)
  block:
    - name: deploy-homelabinfo | Stop and remove existing HomeLabInfo container
      community.docker.docker_container:
        name: "{{ homelabinfo_service_name }}"
        state: absent

    - name: deploy-homelabinfo | Set update HomeLabInfo
      ansible.builtin.set_fact:
        homelabinfo_update: true

- name: deploy-homelabinfo | Deploy HomeLabInfo if not running
  when:
    - not homelabinfo_state.exists or (homelabinfo_update | default(false))
  block:
    - name: deploy-homelabinfo | Pull HomeLabInfo image
      community.docker.docker_image:
        name: "{{ homelabinfo_image }}"
        source: pull

    - name: deploy-homelabinfo | Deploy HomeLabInfo
      community.docker.docker_container:
        name: "{{ homelabinfo_service_name }}"
        image: "{{ homelabinfo_image }}"
        detach: true
        env:
          TZ: "{{ homelab.timezone | default('UTC') }}"
        labels: "{{ homelabinfo_container_labels | default(omit) }}"
        networks_cli_compatible: true
        networks: "{{ homelabinfo_networks | ansible.utils.remove_keys(target=['internal']) | default(omit) }}"
        restart: true
        restart_policy: unless-stopped
        state: started
        volumes: "{{ homelabinfo_volumes | default(omit) }}"
      register: homelabinfo_container_state

- name: deploy-homelabinfo | Wait for HomeLabInfo to accept connections
  ansible.builtin.wait_for:
    host: "{{ homelabinfo_fqdn }}"
    port: 80
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 30
  register: homelabinfo_running
  retries: 10
  until: homelabinfo_running is success
