---
- name: deploy-dozzle-agent | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

####### DOZZLE AGENT SECTION

# https://dozzle.dev/guide/agent

- name: deploy-dozzle-agent | Set Dozzle Agent facts
  ansible.builtin.set_fact:
    dozzle_agent_image: "{{ dozzle_agent_image | default('amir20/dozzle:latest') }}"
    dozzle_agent_service_name: "{{ dozzle_agent_service_name | default('dozzle-agent') }}"
    dozzle_agent_service_port: "{{ dozzle_agent_service_port | default(7007) }}"

- name: deploy-dozzle-agent | Set Dozzle Agent service facts
  ansible.builtin.set_fact:
    # dozzle_agent_networks:
    #   - name: "{{ docker_socket_proxy_network_name | default('docker-socket-proxy') }}"
    #   - name: "{{ montitoring_network_name | default('monitoring') }}"
    #   - name: "{{ web_network_name | default('web') }}"
    dozzle_agent_ports:
      - "{{ dozzle_agent_service_port }}:7007"
    dozzle_agent_volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

- name: deploy-dozzle-agent | Create Dozzle Agent container labels
  ansible.builtin.set_fact:
    dozzle_agent_container_labels: "{{ dozzle_agent_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/amir20/dozzle/releases/tag/v${major}.${minor}.${patch}",
    }

- name: deploy-dozzle-agent | Pull Dozzle Agent image
  community.docker.docker_image:
    name: "{{ dozzle_agent_image }}"
    source: pull

# docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 amir20/dozzle:latest
- name: deploy-dozzle-agent | Deploy Dozzle Agent
  community.docker.docker_container:
    name: "{{ dozzle_agent_service_name }}"
    image: "{{ dozzle_agent_image }}"
    command: agent
    detach: true
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    labels: "{{ (dozzle_agent_container_labels | default({})) | default(omit) }}"
    # networks_cli_compatible: true
    # networks: "{{ dozzle_agent_networks }}"
    published_ports: "{{ dozzle_agent_ports }}"
    restart: true
    restart_policy: unless-stopped
    state: started
    volumes: "{{ dozzle_agent_volumes }}"
  register: dozzle_agent_container_state
