---
- name: deploy-beszel | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

####### BESZEL SECTION

# https://beszel.dev/guide/hub-installation

- name: deploy-beszel | Set Beszel facts
  ansible.builtin.set_fact:
    beszel_image: "{{ beszel_image | default('henrygd/beszel:latest') }}"
    beszel_service_name: "{{ beszel_service_name | default('beszel') }}"
    beszel_service_port: "{{ beszel_service_port | default(8090) }}"

- name: deploy-beszel | Set Beszel network facts
  ansible.builtin.set_fact:
    beszel_network_name: "{{ beszel_network_name | default(beszel_service_name) }}"

- name: deploy-beszel | Set Beszel volume facts
  ansible.builtin.set_fact:
    beszel_volume_name: "{{ beszel_service_name }}"

- name: deploy-beszel | Set Beszel aggregated facts
  ansible.builtin.set_fact:
    beszel_fqdn: "{{ beszel_service_name }}.{{ ansible_hostname }}.{{ homelab.certificate_domain | default('localdomain') }}"

- name: deploy-beszel | Set Beszel service facts
  ansible.builtin.set_fact:
    beszel_networks:
      # Reverse Proxy  network is used to expose applications via Traefik
      - { name: "{{ reverse_proxy_network_name | default('reverse-proxy') }}" }
    beszel_ports:
      # Published ports to expose outside the container
      # host port:container port
      - "{{ beszel_service_port }}:8090"
    beszel_volumes:
      # Local paths to mount into the container
      # local path:container path
      - "{{ beszel_volume_name }}:/beszel_data"

- name: deploy-beszel | Log Beszel configuration
  ansible.builtin.debug:
    msg:
      - "Beszel image: {{ beszel_image }}"
      - "Beszel service name: {{ beszel_service_name }}"
      - "Beszel FQDN: {{ beszel_fqdn }}"
      - "Beszel networks: {{ beszel_networks | default(omit) }}"
      - "Beszel ports: {{ beszel_ports | default(omit) }}"
      - "Beszel volumes: {{ beszel_volumes | default(omit) }}"

- name: deploy-beszel | Create Beszel container labels
  ansible.builtin.set_fact:
    beszel_container_labels: "{{ beszel_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # ---------------------------------------------------------------
    # Homepage labels
    - { "key": "homepage.group", "value": "Monitoring" }
    - { "key": "homepage.name", "value": "Beszel" }
    - {
      "key": "homepage.description",
      "value": "Lightweight server monitoring hub with historical data, docker stats, and alerts.",
    }
    - { "key": "homepage.icon", "value": "beszel.png" }
    - { "key": "homepage.href", "value": "https://{{ beszel_fqdn }}/" }
    - { "key": "homepage.siteMonitor", "value": "https://{{ beszel_fqdn }}/" }
    # ---------------------------------------------------------------
    # Traefik labels
    - { "key": "traefik.enable", "value": "true" }
    - {
      "key": "traefik.http.routers.{{ beszel_service_name }}.entrypoints",
      "value": "{{ traefik_entrypoint_secure_name }}",
    }
    - {
      "key": "traefik.http.routers.{{ beszel_service_name }}.rule",
      "value": "Host(`{{ beszel_fqdn }}`)",
    }
    # ---------------------------------------------------------------
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/henrygd/beszel/releases/tag/v${major}.${minor}.${patch}",
    }

- name: deploy-beszel | Create Beszel network
  when: beszel_networks is defined
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal | default(false) }}"
    state: present
  loop: "{{ beszel_networks }}"

- name: deploy-beszel | Create volume for Beszel
  when: beszel_volume_name is defined and (beszel_volumes | length > 0)
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ beszel_volume_name }}"

- name: deploy-beszel | Pull Beszel image
  community.docker.docker_image:
    name: "{{ beszel_image }}"
    source: pull

- name: deploy-beszel | Deploy Beszel
  community.docker.docker_container:
    name: "{{ beszel_service_name }}"
    image: "{{ beszel_image }}"
    detach: true
    labels: "{{ beszel_container_labels | default(omit) }}"
    networks_cli_compatible: true
    networks: "{{ beszel_networks | ansible.utils.remove_keys(target=['internal']) | default(omit) }}"
    restart: true
    restart_policy: unless-stopped
    state: started
    volumes: "{{ default_host_volumes + beszel_volumes | default(omit) }}"
  register: beszel_container_state

- name: deploy-beszel | Wait for Beszel to accept connections
  ansible.builtin.wait_for:
    host: "{{ beszel_fqdn }}"
    port: 80
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 30
  register: beszel_running
  retries: 10
  until: beszel_running is success
