---

# https://github.com/Finsys/hawser

- name: deploy-hawser | Set Hawser facts
  ansible.builtin.set_fact:
    hawser_image: "{{ hawser_image | default('ghcr.io/finsys/hawser:latest') }}"
    hawser_service_name: "{{ hawser_service_name | default('hawser') }}"
    hawser_service_port: "{{ hawser_service_port | default(2376) }}"
  tags: hawser

- name: deploy-hawser | Set Hawser network facts
  ansible.builtin.set_fact:
    hawser_network_name: "{{ hawser_network_name | default('dockhand') }}"
  tags: hawser

- name: deploy-hawser | Set Hawser volume facts
  ansible.builtin.set_fact:
    hawser_volume_name: "{{ hawser_volume_name | default(hawser_service_name + '_stacks') }}"
  tags: hawser

- name: deploy-hawser | Set Hawser aggregated facts
  ansible.builtin.set_fact:
    hawser_fqdn: "{{ hawser_service_name }}.{{ ansible_facts['hostname'] }}.{{ homelab.certificate_domain | default('localdomain') }}"
  tags: hawser

- name: deploy-hawser | Set Hawser service facts
  ansible.builtin.set_fact:
    hawser_networks:
      - { name: "{{ hawser_network_name }}" }
    hawser_ports:
      - "{{ hawser_service_port }}:2376"
    hawser_volumes:
      - "{{ hawser_volume_name }}:/data/stacks"
  tags: hawser

- name: deploy-hawser | Log Hawser configuration
  ansible.builtin.debug:
    msg:
      - "Hawser image: {{ hawser_image }}"
      - "Hawser service name: {{ hawser_service_name }}"
      - "Hawser FQDN: {{ hawser_fqdn }}"
      - "Hawser networks: {{ hawser_networks | default(omit) }}"
      - "Hawser ports: {{ hawser_ports | default(omit) }}"
      - "Hawser mounts: {{ hawser_volumes | default(omit) }}"
  tags: hawser

- name: deploy-hawser | Create Hawser container labels
  ansible.builtin.set_fact:
    hawser_container_labels: "{{ hawser_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/Finsys/hawser/releases/tag/v${major}.${minor}.${patch}",
    }
  tags: hawser

- name: deploy-hawser | Create Hawser network
  when: hawser_networks is defined
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal | default(false) }}"
    state: present
  loop: "{{ hawser_networks }}"
  tags: hawser

- name: deploy-hawser | Create volume for Hawser Agent
  when: hawser_volumes is defined and (hawser_volumes | length > 0)
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ hawser_volume_name }}"
  tags: hawser

- name: deploy-hawser | Pull Hawser image
  community.docker.docker_image:
    name: "{{ hawser_image }}"
    source: pull
  tags: hawser

- name: deploy-hawser | Deploy Hawser Agent
  community.docker.docker_container:
    name: "{{ hawser_service_name }}"
    image: "{{ hawser_image }}"
    detach: true
    labels: "{{ hawser_container_labels | default(omit) }}"
    networks_cli_compatible: true
    networks: "{{ hawser_networks | ansible.utils.remove_keys(target=['internal']) | default(omit) }}"
    published_ports: "{{ hawser_ports | default(omit) }}"
    restart: true
    restart_policy: unless-stopped
    state: started
    volumes: "{{ docker_host_volume + hawser_volumes | default(omit) }}"
  register: hawser_container_state
  tags: hawser
