---
# Github: https://github.com/open-webui/mcpo
# https://deepwiki.com/open-webui/mcpo/1.2-installation-and-quick-start

- name: deploy-mcpo | Set mcpo facts
  ansible.builtin.set_fact:
    mcpo_image: "{{ mcpo_image | default('ghcr.io/open-webui/mcpo:main') }}"
    mcpo_service_name: "{{ mcpo_service_name | default('mcpo') }}"
    mcpo_service_port: "{{ mcpo_service_port | default(8000) }}"

- name: deploy-mcpo | Set mcpo network facts
  ansible.builtin.set_fact:
    mcpo_open_webui_network_name: "{{ mcpo_open_webui_network_name | default('open-webui') }}"

- name: deploy-mcpo | Set mcpo mount facts
  ansible.builtin.set_fact:
    mcpo_config_dir: "{{ mcpo_config_dir | default('/root/' + mcpo_service_name) }}"
    mcpo_config_file: "config.json"

- name: deploy-mcpo | Set mcpo volume facts
  ansible.builtin.set_fact:
    mcpo_volume_name: "{{ mcpo_volume_name | default(mcpo_service_name) }}"

- name: deploy-mcpo | Set mcpo aggregated facts
  ansible.builtin.set_fact:
    mcpo_fqdn: "{{ mcpo_service_name }}.{{ ansible_facts['hostname'] }}.{{ homelab.certificate_domain | default('localdomain') }}"

- name: deploy-mcpo | Set mcpo service facts
  ansible.builtin.set_fact:
    mcpo_command:
      - "--config"
      - "/app/config.json"
      - "--hot-reload"
      - "--root-path"
      - "/"
      # - "--api-key"
      # - "top-secret"
    mcpo_mounts:
      # Local paths to mount into the container
      # local path:container path
      - "{{ mcpo_config_dir }}/{{ mcpo_config_file }}:/app/{{ mcpo_config_file }}:ro"
    mcpo_networks:
      - { name: "{{ mcpo_open_webui_network_name }}", internal: true }
      # # Reverse Proxy  network is used to expose applications via Traefik
      # - { name: "{{ reverse_proxy_network_name | default('reverse-proxy') }}" }
    mcpo_ports:
      # Published ports to expose outside the container
      # host port:container port
      - "{{ mcpo_service_port }}:8000"
    mcpo_volumes:
      # Volumes to mount into the container
      # volume:container path
      - "{{ mcpo_volume_name }}:/app/data"

- name: deploy-mcpo | Log mcpo configuration
  ansible.builtin.debug:
    msg:
      - "mcpo image: {{ mcpo_image }}"
      - "mcpo service name: {{ mcpo_service_name }}"
      - "mcpo FQDN: {{ mcpo_fqdn }}"
      - "mcpo command: {{ mcpo_command | default(omit) }}"
      - "mcpo networks: {{ mcpo_networks | default(omit) }}"
      - "mcpo ports: {{ mcpo_ports | default(omit) }}"
      - "mcpo mounts: {{ mcpo_mounts | default(omit) }}"
      - "mcpo volumes: {{ mcpo_volumes | default(omit) }}"

- name: deploy-mcpo | Create CHANGE container labels
  ansible.builtin.set_fact:
    mcpo_container_labels: "{{ mcpo_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # ---------------------------------------------------------------
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - { "key": "wud.link.template", "value": "https://github.com/open-webui/mcpo/releases/tag/v${major}.${minor}.${patch}" }

- name: deploy-mcpo | Create mcpo mounts
  when: mcpo_mounts is defined and (mcpo_mounts | length > 0)
  block:

    - name: deploy-mcpo | Create mcpo mount directories
      ansible.builtin.file:
        path: "{{ item }}"
        mode: "0644"
        state: directory
      loop:
        - "{{ mcpo_config_dir }}"

    - name: deploy-mcpo | Create mcpo configuration file
      ansible.builtin.file:
        path: "{{ mcpo_config_dir }}/{{ mcpo_config_file }}"
        mode: "0600"
        state: touch
      register: mcpo_configuration_file_creation

- name: deploy-mcpo | Create mcpo networks
  when: mcpo_networks is defined
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal | default(false) }}"
    state: present
  loop: "{{ mcpo_networks }}"

- name: deploy-mcpo | Create mcpo volumes
  when: mcpo_volumes is defined and (mcpo_volumes | length > 0)
  community.docker.docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ mcpo_volume_name }}"

- name: deploy-mcpo | Pull mcpo image
  community.docker.docker_image:
    name: "{{ mcpo_image }}"
    source: pull

# docker run -p 8000:8000 ghcr.io/open-webui/mcpo:main --api-key "top-secret" -- your_mcp_server_command
- name: deploy-mcpo | Deploy mcpo
  community.docker.docker_container:
    name: "{{ mcpo_service_name }}"
    image: "{{ mcpo_image }}"
    command: "{{ mcpo_command }}"
    detach: true
    env:
      TZ: "{{ homelab.timezone | default('UTC') }}"
    labels: "{{ mcpo_container_labels | default(omit) }}"
    networks_cli_compatible: true
    networks: "{{ mcpo_networks | ansible.utils.remove_keys(target=['internal']) | default(omit) }}"
    published_ports: "{{ mcpo_ports | default(omit) }}"
    restart: true
    restart_policy: unless-stopped
    state: started
    volumes: "{{ mcpo_mounts + mcpo_volumes | default(omit) }}"
  register: mcpo_container_state

- name: deploy-mcpo | Wait for mcpo to accept connections
  when: false
  ansible.builtin.wait_for:
    host: "{{ mcpo_fqdn }}"
    port: 80
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 30
  register: mcpo_running
  retries: 10
  until: mcpo_running is success
