---
- name: deploy-docker-socket-proxy | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy facts
  ansible.builtin.set_fact:
    docker_socket_proxy_image: "{{ docker_socket_proxy_image | default('ghcr.io/tecnativa/docker-socket-proxy:latest') }}"
    docker_socket_proxy_service_name: "{{ docker_socket_proxy_service_name | default('docker-socket-proxy') }}"
    docker_socket_proxy_service_port: "{{ docker_socket_proxy_service_port | default(2375) }}"

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy aggregated facts
  ansible.builtin.set_fact:
    docker_socket_proxy_fqdn: "{{ docker_socket_proxy_service_name }}.{{ ansible_hostname }}.{{ homelab.certificate_domain | default('localdomain') }}"

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy service facts
  ansible.builtin.set_fact:
    docker_socket_proxy_networks:
      - name: "{{ docker_socket_proxy_network_name | default('docker-socket-proxy') }}"
    docker_socket_proxy_ports:
      - "{{ docker_socket_proxy_service_port }}:{{ docker_socket_proxy_service_port }}"

- name: deploy-docker-socket-proxy | Set Docker Socket Proxy configuration facts
  ansible.builtin.set_fact:
    configure_for_docker_volume_backup: "{{ configure_for_docker_volume_backup | default(false) }}"

- name: deploy-docker-socket-proxy | Create Docker Socket Proxy container labels
  ansible.builtin.set_fact:
    docker_socket_proxy_container_labels: "{{ docker_socket_proxy_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/Tecnativa/docker-socket-proxy/releases/tag/v${major}.${minor}.${patch}",
    }

- name: deploy-docker-socket-proxy | Pull Docker Socket Proxy image
  community.docker.docker_image_pull:
    name: "{{ docker_socket_proxy_image }}"
    pull: always

- name: deploy-docker-socket-proxy | Deploy Docker Socket Proxy
  community.docker.docker_container:
    name: "{{ docker_socket_proxy_service_name }}"
    image: "{{ docker_socket_proxy_image }}"
    env:
      LOG_LEVEL: info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      EVENTS: "1"
      PING: "1"
      VERSION: "1"
      ## Revoked by Default
      # Security critical
      AUTH: "0"
      SECRETS: "0"
      POST: "{{ 1 if configure_for_docker_volume_backup else 0 | quote }}" # Allow access for Docker Volume Backup to stop containers
      ## Not always needed
      BUILD: "0"
      COMMIT: "0"
      CONFIGS: "0"
      CONTAINERS: "1" # Allow access to viewing containers (Traefik, Portainer, Docker Volume Backup.)
      DISTRIBUTION: "0"
      EXEC: "{{ 1 if configure_for_docker_volume_backup else 0 | quote }}" # Allow access for Docker Volume Backup to execute commands
      IMAGES: "1" # Allow access to viewing images (Portainer)
      INFO: "1" # Allow access to viewing info (Portainer, Docker Volume Backup)
      NETWORKS: "1" # Allow access to viewing networks (Portainer)
      NODES: "{{ 1 if configure_for_docker_volume_backup else 0 | quote }}" # Allow access for Docker Volume Backup to stop containers
      PLUGINS: "0"
      SERVICES: "1" # Allow access to viewing services (Portainer)
      SESSION: "0"
      SWARM: "0"
      SYSTEM: "0"
      TASKS: "1" # Allow access to viewing tasks (Portainer, Docker Volume Backup)
      VOLUMES: "1" # Allow access to viewing volumes (Portainer)
    labels: "{{ docker_socket_proxy_container_labels }}"
    networks: "{{ docker_socket_proxy_networks }}"
    published_ports: "{{ docker_socket_proxy_ports }}"
    recreate: true # Recreate to ensure env changes are used
    restart: true
    restart_policy: unless-stopped
    security_opts:
      - no-new-privileges=true
    state: started
    volumes: "{{ default_host_volumes + docker_host_volume }}"
  register: docker_socket_proxy_container_state

- name: deploy-docker-socket-proxy | Wait for Docker Socket Proxy to accept connections
  ansible.builtin.wait_for:
    host: "{{ docker_socket_proxy_container_state['container']\
      ['NetworkSettings']\
      ['Networks']\
      [docker_socket_proxy_service_name]\
      ['IPAddress'] }}"
    port: "{{ docker_socket_proxy_service_port }}"
    connect_timeout: 1
    delay: 10
    state: started
    timeout: 30
  register: docker_socket_proxy_running
  retries: 10
  until: docker_socket_proxy_running is success
