---

- name: deploy-homebox | Ensure modern version of Docker is available on host
  ansible.builtin.include_tasks:
    file: tasks/hosts-dependency-check-docker-version.yaml

- name: deploy-homebox | Set Homebox facts
  ansible.builtin.set_fact:
    homebox_image: "{{ homebox_image | default('ghcr.io/hay-kot/homebox:latest') }}"
    homebox_service_name: "{{ homebox_service_name | default('homebox') }}"
    homebox_service_port: "{{ homebox_service_port | default(7745) }}"
    homebox_volume_name: "{{ homebox_volume_name | default('homebox') }}"

- name: deploy-homebox | Set Homebox aggregated facts
  ansible.builtin.set_fact:
    homebox_fqdn: "{{ homebox_service_name }}.{{ ansible_hostname }}.{{ homelab.lan_domain | default('localdomain') }}"

- name: deploy-homebox | Set Homebox service facts
  ansible.builtin.set_fact:
    homebox_networks:
      - name: "{{ web_network_name | default('web') }}"
    homebox_ports:
      # Published ports to expose outside the container
      # host port:container port
      - "{{ homebox_service_port }}:7745"
    homebox_volumes:
      # Local paths to mount into the container
      # local path:container path
      - "{{ homebox_volume_name }}:/data"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

- name: deploy-homebox | Create Homebox container labels
  ansible.builtin.set_fact:
    homebox_container_labels: "{{ homebox_container_labels | default({}) | combine({item.key: item.value}) }}"
  with_items:
    # ---------------------------------------------------------------
    # Traefik labels
    - { "key": "traefik.enable", "value": "true" }
    - {
      "key": "traefik.http.routers.{{ homebox_service_name }}.entrypoints",
      "value": "websecure",
    }
    - {
      "key": "traefik.http.routers.{{ homebox_service_name }}.rule",
      "value": "Host(`{{ homebox_fqdn }}`)",
    }
    # - {
    #   "key": "traefik.http.routers.{{ homebox_service_name }}.service",
    #   "value": "{{ homebox_service_name }}",
    # }
    # - {
    #   "key": "traefik.http.routers.{{ homebox_service_name }}.tls",
    #   "value": "true",
    # }
    # ---------------------------------------------------------------
    # What's up Docker? labels
    - { "key": "wud.tag.include", "value": '^\d+\.\d+\.\d+$$' }
    - {
      "key": "wud.link.template",
      "value": "https://github.com/sysadminsmedia/homebox/releases/tag/v${major}.${minor}.${patch}",
    }
    # ---------------------------------------------------------------
    # Docker Volume Backup labels
    - { "key": "docker-volume-backup.stop-during-backup", "value": "true" }
    # ---------------------------------------------------------------
    # Homepage labels
    - { "key": "homepage.group", "value": "Applications" }
    - { "key": "homepage.name", "value": "Homebox" }
    - { "key": "homepage.description", "value": "What's in the house?" }
    - { "key": "homepage.icon", "value": "homebox.png" }
    - { "key": "homepage.href", "value": "https://{{ homebox_fqdn }}/" }
    - {
      "key": "homepage.siteMonitor",
      "value": "https://{{ homebox_fqdn }}/",
    }
    - { "key": "homepage.widget.type", "value": "homebox" }
    - {
      "key": "homepage.widget.url",
      "value": "https://{{ homebox_fqdn }}",
    }
    - { "key": "homepage.widget.username", "value": "{{ homebox.username }}" }
    - { "key": "homepage.widget.password", "value": "{{ homebox.password }}" }
    - { "key": "homepage.widget.fields", "value": "['items', 'locations', 'totalValue']" }

- name: deploy-homebox | Create Homebox volume
  community.docker.docker_volume:
    name: "{{ homebox_volume_name }}"
    state: present

- name: deploy-homebox | Check if Homebox is running
  community.docker.docker_container_info:
    name: "{{ homebox_service_name }}"
  register: homebox_state

- name: deploy-homebox | Remove Homebox container if changing version
  when:
    - homebox_state.exists
    - (homebox_image  | split(':') | last) != (homebox_state.container.Config.Image | split(':') | last)
  block:
    - name: deploy-homebox | Stop and remove existing Homebox container
      community.docker.docker_container:
        name: "{{ homebox_service_name }}"
        state: absent

    - name: deploy-homebox | Set update Homebox
      ansible.builtin.set_fact:
        homebox_update: true

- name: deploy-homebox | Deploy Homebox if not running
  when: not homebox_state.exists or (homebox_update | default(false))
  block:
    - name: deploy-homebox | Pull homebox image
      community.docker.docker_image:
        name: "{{ homebox_image }}"
        source: pull

    # docker run -d -p 3000:3000 homebox/homebox
    - name: deploy-homebox | Deploy Homebox
      community.docker.docker_container:
        name: "{{ homebox_service_name }}"
        image: "{{ homebox_image }}"
        detach: true
        env:
          HBOX_LOG_LEVEL: "info"
          HBOX_LOG_FORMAT: "json"
          HBOX_WEB_MAX_UPLOAD_SIZE: "10"
          TZ: "{{ homelab.timezone | default(omit) }}"
        labels: "{{ homebox_container_labels | default(omit) }}"
        networks_cli_compatible: true
        networks: "{{ homebox_networks }}"
        restart: true
        restart_policy: unless-stopped
        state: started
        volumes: "{{ homebox_volumes }}"
      register: homebox_container_state

    - name: deploy-homebox | Wait for Homebox to accept connections
      ansible.builtin.wait_for:
        host: "{{ homebox_fqdn }}"
        port: 80
        connect_timeout: 1
        delay: 10
        state: started
        timeout: 30
      register: homebox_running
      until: homebox_running is success
      retries: 10
