---

- name: Load homelab vars
  ansible.builtin.include_vars:
    file: vars/homelab_env.yaml

- name: Configure base OS
  ansible.builtin.include_tasks:
    file: tasks/hosts-configure-base-os.yaml

- name: Check Docker is available  # noqa: syntax-check[unknown-module]
  community.docker.docker_host_info:
  register: host_docker_info
  ignore_errors: true

- name: Install Docker
  when: host_docker_info.can_talk_to_docker is defined
  ansible.builtin.import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: false
    docker_users:
      - root

- name: Create Docker networks  # noqa: syntax-check[unknown-module]
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver }}"
    internal: "{{ item.internal }}"
  loop:
    - name: "{{ docker_socket_proxy_network_name | default('docker-socket-proxy') }}"
      driver: bridge
      internal: true
    - name: "{{ monitoring_network_name | default('monitoring') }}"
      driver: bridge
      internal: true
    - name: "{{ web_network_name | default('web') }}"
      driver: bridge
      internal: false

- name: Deploy a containerised instance of Docker Socket Proxy
  ansible.builtin.include_tasks:
    file: tasks/deploy-docker-socket-proxy.yaml

- name: Deploy a containerised instance of Portainer Agent
  ansible.builtin.include_tasks:
    file: tasks/deploy-portainer-agent.yaml

- name: Deploy a containerised instance of Traefik
  ansible.builtin.include_tasks:
    file: tasks/deploy-traefik.yaml

# - name: Deploy a containerised instance of Node Exporter
#   ansible.builtin.include_tasks:
#     file: tasks/deploy-node-exporter.yaml

# - name: Deploy a containerised instance of Prometheus
#   ansible.builtin.include_tasks:
#     file: tasks/deploy-prometheus.yaml

- name: Deploy a containerised instance of Dozzle Agent
  ansible.builtin.include_tasks:
    file: tasks/deploy-dozzle-agent.yaml
