---

- name: hosts-apt-update | Update packages with apt
  when: ansible_pkg_mgr == 'apt'
  ansible.builtin.apt:
    update_cache: true

- name: hosts-apt-update | Upgrade packages with apt
  when: ansible_pkg_mgr == 'apt'
  ansible.builtin.apt:
    upgrade: dist
