---

- name: load-images | Copy to host image {{ item.name }}
  ansible.builtin.copy:
    src: /tmp/images/{{ item.name }}.tar
    dest: /tmp/{{ item.name }}.tar
    mode: "0644"

- name: load-images | Load image {{ item.name }}  # noqa: syntax-check[unknown-module]
  community.docker.docker_image:
    name: "{{ item.image }}"
    tag: "{{ item.tag }}"
    load_path: "/tmp/{{ item.name }}.tar"
    source: load
    mode: "0644"
    state: present
