---

- name: save-images | Archive image {{ item.image }}  # noqa: syntax-check[unknown-module]
  community.docker.docker_image:
    name: "{{ item.image }}"
    tag: "{{ item.tag }}"
    archive_path: "/tmp/{{ item.name }}.tar"
    source: pull
    state: present

- name: save-images | Copy, to ansible host, image {{ item.name }}
  ansible.builtin.fetch:
    src: /tmp/{{ item.name }}.tar
    dest: /tmp/images/
    flat: true
