---

- name: Archive image {{ item.image }}
  community.docker.docker_image:
    name: "{{ item.image }}"
    tag: "{{ item.tag }}"
    archive_path: "/tmp/{{ item.name }}.tar"
    source: pull
    mode: "0644"
    state: present

- name: Copy, to ansible host, image {{ item.name }}
  ansible.builtin.fetch:
    src: /tmp/{{ item.name }}.tar
    dest: /tmp/images/
    flat: true
