---
- name: Deploy Ollama

  hosts: ollama

  vars:

    # Ollama facts
    # renovate: datasource=docker depName=ollama/ollama
    ollama_image: ollama/ollama:0.11.10

    # Open WebUI facts
    # renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
    open_webui_image: ghcr.io/open-webui/open-webui:0.6.26

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Ollama
      ansible.builtin.include_tasks:
        file: tasks/deploy-ollama.yaml

    - name: Deploy a containerised instance of Open WebUI
      ansible.builtin.include_tasks:
        file: tasks/deploy-open-webui.yaml
