---
- name: Deploy EMQX

  hosts: messaging

  vars:

    # EMQX facts
    # renovate: datasource=docker depName=emqx/emqx
    emqx_image: emqx/emqx:6.2.1

  pre_tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:

    - name: Deploy a containerised instance of EMQX
      ansible.builtin.include_tasks:
        file: tasks/deploy-emqx.yaml
