---

# Attempts to deploy Nextcloud behind Traefik as a reverse proxy
#
# https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
# https://heiden.io/2023/11/27/setting-up-nextcloud-all-in-one-aio-with-a-traefik-v3-reverse-proxy/


- name: Deploy Nextcloud AIO stack

  hosts: nextcloud

  vars:

    # Nextcloud All-in-One facts
    # renovate: datasource=docker depName=ghcr.io/nextcloud-releases/all-in-one
    nextcloud_aio_mastercontainer_image: ghcr.io/nextcloud-releases/all-in-one:latest

  pre_tasks:

    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Traefik for Nextcloud
      ansible.builtin.include_tasks:
        file: tasks/deploy-traefik-nextcloud.yaml

    - name: Deploy a containerised instance of Traefik Manager
      when: false
      ansible.builtin.include_tasks:
        file: tasks/deploy-traefik-manager.yaml

    - name: Deploy a containerised instance of Nextcloud All-in-One
      ansible.builtin.include_tasks:
        file: tasks/deploy-nextcloud-aio-mastercontainer.yaml
