---
- name: Deploy Productivity Stack

  hosts: productivity

  vars:

    # Affine facts
    # renovate: datasource=docker depName=ghcr.io/toeverything/affine
    affine_image: ghcr.io/toeverything/affine:0.26.7
    affine_deploy_docker_volume_backup: true

    # BentoPDF facts
    # renovate: datasource=docker depName=ghcr.io/alam00000/bentopdf
    bentopdf_image: ghcr.io/alam00000/bentopdf:2.8.5

    # Grist facts
    # renovate: datasource=docker depName=gristlabs/grist
    grist_image: gristlabs/grist:1.7.15
    grist_deploy_docker_volume_backup: false

    # OmniTools facts
    # renovate: datasource=docker depName=iib0011/omni-tools
    omnitools_image: iib0011/omni-tools:0.6.0

    # Tududi facts
    # renovate: datasource=docker depName=chrisvel/tududi
    tududi_image: chrisvel/tududi:1.1.0
    tududi_deploy_docker_volume_backup: true

    # Vert facts
    # renovate: datasource=docker depName=ghcr.io/vert-sh/vert
    vert_image: ghcr.io/vert-sh/vert:latest

  pre_tasks:

    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:

    - name: Deploy a containerised instance of AFFiNE
      ansible.builtin.include_tasks:
        file: tasks/deploy-affine.yaml

    - name: Deploy a containerised instance of BentoPDF
      ansible.builtin.include_tasks:
        file: tasks/deploy-bentopdf.yaml

    - name: Deploy a containerised instance of Grist
      ansible.builtin.include_tasks:
        file: tasks/deploy-grist.yaml

    - name: Deploy a containerised instance of OmniTools
      ansible.builtin.include_tasks:
        file: tasks/deploy-omnitools.yaml

    - name: Deploy a containerised instance of Tududi
      ansible.builtin.include_tasks:
        file: tasks/deploy-tududi.yaml

    - name: Deploy a containerised instance of VERT
      ansible.builtin.include_tasks:
        file: tasks/deploy-vert.yaml
