---
- name: Deploy Uptime Kuma

  hosts: monitor

  vars:

    # Uptime Kuma facts
    # renovate: datasource=docker depName=louislam/uptime-kuma
    uptimekuma_image: louislam/uptime-kuma:2.2.1-slim

    uptimekuma_deploy_docker_volume_backup: false

  pre_tasks:

      - name: Ensure base environment is configured
        ansible.builtin.include_tasks:
          file: tasks/configure-containerised-base.yaml

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Uptime Kuma
      ansible.builtin.include_tasks:
        file: tasks/deploy-uptimekuma.yaml
