---
- name: Deploy Uptime Kuma

  hosts: uptimekuma

  vars:

    # Uptime Kuma facts
    # renovate: datasource=docker depName=louislam/uptime-kuma
    uptimekuma_image: louislam/uptime-kuma:1.23.17-alpine

    uptimekuma_deploy_docker_volume_backup: false

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Uptime Kuma
      ansible.builtin.include_tasks:
        file: tasks/deploy-uptimekuma.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: uptimekuma_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup-{{ uptimekuma_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ uptimekuma_volume_name }}:/backup/{{ uptimekuma_service_name }}-backup:ro"
        docker_volume_backup_backup_label: "{{ uptimekuma_service_name }}"
        docker_volume_backup_backup_retention_days: 1
