---

- name: Deploy Authentik

  hosts: home

  vars:

    # Authentik facts
    # renovate: datasource=docker depName=ghcr.io/goauthentik/server
    authentik_image: ghcr.io/goauthentik/server:2026.2.3

  pre_tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of Authentik
      ansible.builtin.include_tasks:
        file: tasks/deploy-authentik.yaml
