---
- name: Deploy Uptime Kuma

  hosts: uptimekuma

  vars:

    # Uptime Kuma facts
    uptimekuma_image: louislam/uptime-kuma:1.23.16-alpine

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Uptime Kuma
      ansible.builtin.include_tasks:
        file: tasks/deploy-uptimekuma.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_volume_to_backup:
          - "{{ uptimekuma_volume_name }}:/backup/uptimekuma-backup:ro"
        docker_volume_backup_backup_label: "{{ uptimekuma_service_name }}"
        docker_volume_backup_backup_retention_days: 1
