---
- name: Deploy Tududi

  hosts: productivity

  vars:

    # Tududi facts
    # renovate: datasource=docker depName=chrisvel/tududi
    tududi_image: chrisvel/tududi:1.1.0
    tududi_deploy_docker_volume_backup: true

  pre_tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of Tududi
      ansible.builtin.include_tasks:
        file: tasks/deploy-tududi.yaml
