---
- name: Deploy Messaging Stack

  hosts: messaging

  vars:

    # EMQX facts
    # renovate: datasource=docker depName=emqx/emqx
    emqx_image: emqx/emqx:6.2.0

    # Gotify facts
    # renovate: datasource=docker depName=gotify/server
    gotify_image: gotify/server:2.9.1

    # Ntfy facts
    # renovate: datasource=docker depName=binwiederhier/ntfy
    ntfy_image: binwiederhier/ntfy:v2.22.0

  pre_tasks:
    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    ########### Deploy EMQX
    - name: Deploy a containerised instance of EMQX
      ansible.builtin.include_tasks:
        file: tasks/deploy-emqx.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: emqx_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup_{{ emqx_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ emqx_volume_data_name }}:/backup/{{ emqx_service_name }}_backup:ro"
        docker_volume_backup_backup_label: "{{ emqx_service_name }}"
        docker_volume_backup_backup_retention_days: 3

    ########### Deploy Gotify
    - name: Deploy a containerised instance of Gotify
      ansible.builtin.include_tasks:
        file: tasks/deploy-gotify.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: gotify_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup_{{ gotify_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ gotify_volume_name }}:/backup/{{ gotify_service_name }}_backup:ro"
        docker_volume_backup_backup_label: "{{ gotify_service_name }}"
        docker_volume_backup_backup_retention_days: 7

    ########### Deploy Ntfy
    - name: Deploy a containerised instance of Ntfy
      ansible.builtin.include_tasks:
        file: tasks/deploy-ntfy.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: ntfy_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup_{{ ntfy_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ ntfy_volume_name }}:/backup/{{ ntfy_service_name }}_backup:ro"
        docker_volume_backup_backup_label: "{{ ntfy_service_name }}"
        docker_volume_backup_backup_retention_days: 7
