---
- name: Deploy Homelab Controller Node

  hosts: controller

  vars:

    # Dockhand facts
    # renovate: datasource=docker depName=fnsys/dockhand
    dockhand_image: fnsys/dockhand:v1.0.29

    # Semaphore facts
    # renovate: datasource=docker depName=semaphoreui/semaphore
    semaphore_image: semaphoreui/semaphore:v2.18.4
    semaphore_deploy_docker_volume_backup: true

    # Termix facts
    # renovate: datasource=docker depName=ghcr.io/lukegus/termix
    termix_image: ghcr.io/lukegus/termix:release-2.2.1

    # IT-Tools facts
    # renovate: datasource=docker depName=corentinth/it-tools
    it_tools_image: corentinth/it-tools:2024.10.22-7ca5933

    # Networking Toolbox facts
    # renovate: datasource=docker depName=lissy93/networking-toolbox
    networking_toolbox_image: lissy93/networking-toolbox:1.6.0

    # TODO
    #
    # Add:
      # HomeLabInfo
      # Homelable

  pre_tasks:

    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

    # Load environment variables applicable to the homelab environment
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:

    - name: Deploy a containerised instance of Dockhand
      ansible.builtin.include_tasks:
        file: tasks/deploy-dockhand.yaml

    - name: Deploy a containerised instance of Termix
      ansible.builtin.include_tasks:
        file: tasks/deploy-termix.yaml

    - name: Deploy a containerised instance of Semaphore
      ansible.builtin.include_tasks:
        file: tasks/deploy-semaphore.yaml

    - name: Deploy a containerised instance of IT-Tools
      ansible.builtin.include_tasks:
        file: tasks/deploy-it_tools.yaml

    - name: Deploy a containerised instance of Networking Toolbox
      ansible.builtin.include_tasks:
        file: tasks/deploy-networking-toolbox.yaml
