---
- name: Deploy Home Stack

  hosts: home

  vars:

    # Authentik facts
    # renovate: datasource=docker depName=ghcr.io/goauthentik/server
    authentik_image: ghcr.io/goauthentik/server:2026.2.3

    # Homepage facts
    # renovate: datasource=docker depName=ghcr.io/gethomepage/homepage
    homepage_image: ghcr.io/gethomepage/homepage:v1.13.1

    # SearXNG facts
    # renovate: datasource=docker depName=searxng/searxng
    searxng_image: searxng/searxng:2026.5.17-d7e8b7cd1

    # Vaultwarden facts
    # renovate: datasource=docker depName=vaultwarden/server
    vaultwarden_image: vaultwarden/server:1.36.0-alpine
    vaultwarden_deploy_docker_volume_backup: true

  pre_tasks:

    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:

    - name: Deploy a containerised instance of Authentik
      ansible.builtin.include_tasks:
        file: tasks/deploy-authentik.yaml

    - name: Deploy a containerised instance of Homepage
      ansible.builtin.include_tasks:
        file: tasks/deploy-homepage.yaml

    - name: Deploy a containerised instance of SearXNG
      ansible.builtin.include_tasks:
        file: tasks/deploy-searxng.yaml

    - name: Deploy a containerised instance of Vaultwarden
      ansible.builtin.include_tasks:
        file: tasks/deploy-vaultwarden.yaml
