---
- name: Deploy Monitor stack

  hosts: monitor

  vars:
    # Beszel facts
    # renovate: datasource=docker depName=henrygd/beszel
    beszel_image: henrygd/beszel:0.18.7

    # Dozzle facts
    # Ensure values are also set in group_vars/homelab_lxc_docker.yaml.
    # TODO: Ensure variables set here are used in group_vars
    # renovate: datasource=docker depName=amir20/dozzle
    dozzle_image: amir20/dozzle:v10.5.0

    # Uptime Kuma facts
    # renovate: datasource=docker depName=louislam/uptime-kuma
    uptimekuma_image: louislam/uptime-kuma:2.2.1-slim
    uptimekuma_deploy_docker_volume_backup: false

    # What's up Docker? facts
    # renovate: datasource=docker depName=getwud/wud
    wud_image: getwud/wud:8.2.2

  pre_tasks:
    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

  tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Beszel
      ansible.builtin.include_tasks:
        file: tasks/deploy-beszel.yaml

    - name: Deploy a containerised instance of Dozzle
      ansible.builtin.include_tasks:
        file: tasks/deploy-dozzle.yaml

    - name: Deploy a containerised instance of Uptime Kuma
      ansible.builtin.include_tasks:
        file: tasks/deploy-uptimekuma.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: uptimekuma_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup-{{ uptimekuma_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ uptimekuma_volume_name }}:/backup/{{ uptimekuma_service_name }}-backup:ro"
        docker_volume_backup_backup_label: "{{ uptimekuma_service_name }}"
        docker_volume_backup_backup_retention_days: 1

    - name: Deploy a containerised instance of What's up Docker?
      ansible.builtin.include_tasks:
        file: tasks/deploy-wud.yaml
