---
- name: Deploy Broker

  hosts: broker

  vars:

    # Gotify facts
    # renovate: datasource=docker depName=gotify/server
    gotify_image: gotify/server:2.7.3

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Gotify
      ansible.builtin.include_tasks:
        file: tasks/deploy-gotify.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: gotify_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup-{{ gotify_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ gotify_volume_name }}:/backup/{{ gotify_service_name }}-backup:ro"
        docker_volume_backup_backup_label: "{{ gotify_service_name }}"
        docker_volume_backup_backup_retention_days: 7
