---

- name: Deploy Zot

  hosts: ansible

  vars:

    # Zot facts
    # renovate: datasource=docker depName=ghcr.io/project-zot/zot-linux-amd64
    zot_image: ghcr.io/project-zot/zot-linux-amd64:v2.1.10

    zot_deploy_docker_volume_backup: false

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Zot
      ansible.builtin.include_tasks:
        file: tasks/deploy-zot.yaml
