---
- name: Deploy VolumeVault

  hosts: lxc-controller

  vars:

    # Termix facts
    # renovate: datasource=docker depName=ghcr.io/darkdragon14/volumevault
    volumevault_image: ghcr.io/darkdragon14/volumevault:v1.8.0

  pre_tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of VolumeVault
      ansible.builtin.include_tasks:
        file: tasks/deploy-volumevault.yaml
