---
- name: Deploy Broker

  hosts: broker

  vars:

    # Gotify facts
    # renovate: datasource=docker depName=gotify/server
    gotify_image: gotify/server:2.6.3

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Gotify
      ansible.builtin.include_tasks:
        file: tasks/deploy-gotify.yaml
