---

- name: Deploy InfluxDB

  hosts: influxdb

  vars:

    # InfluxDB facts
    influxdb_image_name: influxdb
    influxdb_image_tag: 2.7.11-alpine
    influxdb_service_name: influxdb
    influxdb_service_port: 8086
    influxdb_config_volume_name: influxconfig
    influxdb_data_volume_name: influxdata

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of InfluxDB
      ansible.builtin.include_tasks:
        file: tasks/deploy-influxdb.yaml
