---
- name: Deploy Plant-it

  hosts: plant-it

  vars:

    # Plant-it facts
    plant_it_image: msdeluise/plant-it-server:0.10.0
    plant_it_service_name: plant-it
    plant_it_service_port_ui: 3000
    plant_it_service_port_api: 8080
    plant_it_upload_volume_name: plant_it_upload
    plant_it_db_backup_volume_name: plant_it_db_backup

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Plant-it
      ansible.builtin.include_tasks:
        file: tasks/deploy-plant_it.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_volume_to_backup:
          - "{{ plant_it_db_backup_volume_name }}:/backup/plant_it_db-backup:ro"
        docker_volume_backup_backup_label: "{{ plant_it_service_name }}-db"
