---
- name: Deploy Uptimekuma

  hosts: uptimekuma

  vars:

    # Uptimekuma facts
    uptimekuma_image_name: louislam/uptime-kuma
    uptimekuma_image_tag: 1.23.16-alpine
    uptimekuma_service_name: uptimekuma
    uptimekuma_service_port: 3001
    uptimekuma_volume_name: uptimekuma

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Uptimekuma
      ansible.builtin.include_tasks:
        file: tasks/deploy-uptimekuma.yaml
