---
- name: Deploy Chrony

  hosts: chrony

  vars:

    # Chrony facts
    # renovate: datasource=docker depName=dockurr/chrony
    chrony_image: dockurr/chrony:latest

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Chrony
      ansible.builtin.include_tasks:
        file: tasks/deploy-chrony.yaml
