---
- name: Deploy Homebox

  hosts: inventories

  vars:

    # Homebox facts
    # renovate: datasource=docker depName=ghcr.io/sysadminsmedia/homebox
    homebox_image: ghcr.io/sysadminsmedia/homebox:0.26.2
    homebox_deploy_docker_volume_backup: true

  pre_tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:

    - name: Deploy a containerised instance of Homebox
      ansible.builtin.include_tasks:
        file: tasks/deploy-homebox.yaml
