---
- name: Deploy Journal

  hosts: journal

  vars:

    # Journal facts
    # journal_image: ghcr.io/getjournal/journal:v0.10.9
    journal_service_name: journal
    journal_service_port: 3000

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Journal
      ansible.builtin.include_tasks:
        file: tasks/deploy-journal.yaml
