---
- name: Deploy Semaphore

  hosts: lxc-controller

  vars:

    # Semaphore facts
    # renovate: datasource=docker depName=semaphoreui/semaphore
    semaphore_image: semaphoreui/semaphore:v2.17.36

    semaphore_deploy_docker_volume_backup: false

  pre_tasks:

    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

  tasks:

    # Load environment variables applicable to the homelab environment
    - name: homelab-deploy-support-services | Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Semaphore
      ansible.builtin.include_tasks:
        file: tasks/deploy-semaphore.yaml
