---
- name: Deploy Semaphore

  hosts: controller

  vars:

    # Semaphore facts
    # renovate: datasource=docker depName=semaphoreui/semaphore
    semaphore_image: semaphoreui/semaphore:v2.18.4
    semaphore_deploy_docker_volume_backup: true

  pre_tasks:

    # Load environment variables applicable to the homelab environment
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of Semaphore
      ansible.builtin.include_tasks:
        file: tasks/deploy-semaphore.yaml
