---
- name: Deploy Chrony

  hosts: chrony

  vars:

    # Chrony facts
    chrony_image: dockurr/chrony:latest
    chrony_service_name: chrony
    chrony_service_port: 123

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Chrony
      ansible.builtin.include_tasks:
        file: tasks/deploy-chrony.yaml
