---
- name: Deploy n8n

  hosts: ai

  vars:
    # n8n facts
    # renovate: datasource=docker depName=n8nio/n8n
    n8n_image: n8nio/n8n:2.25.1

  pre_tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of n8n
      ansible.builtin.include_tasks:
        file: tasks/deploy-n8n.yaml
