---

- name: Deploy n8n

  hosts: ollama

  vars:

    # n8n facts
    # renovate: datasource=docker depName=docker.n8n.io/n8nio/n8n
    n8n_image: docker.n8n.io/n8nio/n8n:2.15.0

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of n8n
      ansible.builtin.include_tasks:
        file: tasks/deploy-n8n.yaml
