---
- name: Deploy What's up Docker?

  hosts: whatsupdocker

  vars:

    # What's up Docker? facts
    whatsupdocker_image_name: getwud/wud:8.0.1
    whatsupdocker_service_name: whats-up-docker
    whatsupdocker_service_port: 3000
    whatsupdocker_volume_name: whats-up-docker

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of What's up Docker?
      ansible.builtin.include_tasks:
        file: tasks/deploy-whatsupdocker.yaml
