---
- name: Deploy SearXNG

  hosts: home

  pre_tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of SearXNG
      ansible.builtin.include_tasks:
        file: tasks/deploy-searxng.yaml
