---
- name: Deploy Docmost

  hosts: productivity

  vars:

    # Docmost facts
    # renovate: datasource=docker depName=docmost/docmost
    docmost_image: docmost/docmost:0.23.1

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Docmost
      ansible.builtin.include_tasks:
        file: tasks/deploy-docmost.yaml
