---
- name: Deploy EMQX

  hosts: broker

  vars:

    # EMQX facts
    # renovate: datasource=docker depName=emqx/emqx
    emqx_image: emqx/emqx:5.8.8

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of EMQX
      ansible.builtin.include_tasks:
        file: tasks/deploy-emqx.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup-{{ emqx_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ emqx_volume_data_name }}:/backups/{{ emqx_service_name }}-backup:ro"
        docker_volume_backup_backup_label: "{{ emqx_service_name }}"
        docker_volume_backup_backup_retention_days: 3
