---
- name: Deploy Ntfy

  hosts: messaging

  vars:

    # Ntfy facts
    # renovate: datasource=docker depName=binwiederhier/ntfy
    ntfy_image: binwiederhier/ntfy:v2.23.0
    ntfy_deploy_docker_volume_backup: true

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Ntfy
      ansible.builtin.include_tasks:
        file: tasks/deploy-ntfy.yaml
