---
- name: Deploy Termix

  hosts: lxc-controller

  vars:

    # Termix facts
    # renovate: datasource=docker depName=ghcr.io/lukegus/termix
    termix_image: ghcr.io/lukegus/termix:release-2.4.0
    termix_deploy_docker_volume_backup: true

  pre_tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of Termix
      ansible.builtin.include_tasks:
        file: tasks/deploy-termix.yaml
