---
- name: Deploy What's up Docker?

  hosts: dozzle

  vars:

    # What's up Docker? facts
    # renovate: datasource=docker depName=getwud/wud
    whatsupdocker_image: getwud/wud:8.1.1

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of What's up Docker?
      ansible.builtin.include_tasks:
        file: tasks/deploy-whatsupdocker.yaml
