---
- name: Deploy Uptime Kuma

  hosts: monitor

  vars:

    # Uptime Kuma facts
    # renovate: datasource=docker depName=louislam/uptime-kuma
    uptimekuma_image: louislam/uptime-kuma:2.4.0-slim
    uptimekuma_deploy_docker_volume_backup: true

  pre_tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of Uptime Kuma
      ansible.builtin.include_tasks:
        file: tasks/deploy-uptimekuma.yaml
