---
- name: Deploy LLM stack

  hosts: ollama

  vars:
    # Ollama facts
    # renovate: datasource=docker depName=ollama/ollama
    ollama_image: ollama/ollama:0.23.2

    # SearXNG facts
    # renovate: datasource=docker depName=searxng/searxng
    searxng_image: searxng/searxng:2026.5.10-df1f24fb7

    # Open WebUI facts
    # renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
    open_webui_image: ghcr.io/open-webui/open-webui:0.9.5-slim
    open_webui_network_name: open-webui

    # n8n facts
    # renovate: datasource=docker depName=docker.n8n.io/n8nio/n8n
    n8n_image: n8nio/n8n:2.21.0

  pre_tasks:
    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

  tasks:
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Ollama
      ansible.builtin.include_tasks:
        file: tasks/deploy-ollama.yaml
      vars:
        ollama_network_name: "{{ open_webui_network_name }}"

    - name: Deploy a containerised instance of SearXNG
      ansible.builtin.include_tasks:
        file: tasks/deploy-searxng.yaml
      vars:
        searxng_network_name: "{{ open_webui_network_name }}"

    # Open WebUI is configured to use Ollama as its backend LLM provider
    # and SearXNG as its search engine provider.
    # Expects Ollama and SearXNG to be running on the same network.
    - name: Deploy a containerised instance of Open WebUI
      ansible.builtin.include_tasks:
        file: tasks/deploy-open-webui.yaml

    - name: Deploy a containerised instance of n8n
      ansible.builtin.include_tasks:
        file: tasks/deploy-n8n.yaml
