---
- name: Deploy Ollama

  hosts: ollama

  vars:

    # Ollama facts
    # renovate: datasource=docker depName=ollama/ollama
    ollama_image: ollama/ollama:0.12.4

    # SearXNG facts
    # renovate: datasource=docker depName=searxng/searxng
    searxng_image: searxng/searxng:2025.10.10-f0dfe3cc0

    # Open WebUI facts
    # renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
    open_webui_image: ghcr.io/open-webui/open-webui:0.6.33
    open_webui_network_name: open-webui

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Ollama
      ansible.builtin.include_tasks:
        file: tasks/deploy-ollama.yaml
      vars:
        ollama_network_name: "{{ open_webui_network_name }}"

    - name: Deploy a containerised instance of SearXNG
      ansible.builtin.include_tasks:
        file: tasks/deploy-searxng.yaml
      vars:
        searxng_network_name: "{{ open_webui_network_name }}"

    # Open WebUI is configured to use Ollama as its backend LLM provider
    # and SearXNG as its search engine provider.
    # Expects Ollama and SearXNG to be running on the same host.
    - name: Deploy a containerised instance of Open WebUI
      ansible.builtin.include_tasks:
        file: tasks/deploy-open-webui.yaml
