---
- name: Deploy Messaging Stack

  hosts: messaging

  vars:

    # EMQX facts
    # renovate: datasource=docker depName=emqx/emqx
    emqx_image: emqx/emqx:6.2.0

    # Gotify facts
    # renovate: datasource=docker depName=gotify/server
    gotify_image: gotify/server:2.9.1

    # Ntfy facts
    # renovate: datasource=docker depName=binwiederhier/ntfy
    ntfy_image: binwiederhier/ntfy:v2.23.0

  pre_tasks:

    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:

    ########### Deploy EMQX
    - name: Deploy a containerised instance of EMQX
      ansible.builtin.include_tasks:
        file: tasks/deploy-emqx.yaml

    ########### Deploy Gotify
    - name: Deploy a containerised instance of Gotify
      ansible.builtin.include_tasks:
        file: tasks/deploy-gotify.yaml

    ########### Deploy Ntfy
    - name: Deploy a containerised instance of Ntfy
      ansible.builtin.include_tasks:
        file: tasks/deploy-ntfy.yaml
