---
- name: Deploy Homelab Controller Node

  hosts: lxc-controller

  vars:
    # Gitea facts
    # renovate: datasource=docker depName=docker.gitea.com/gitea
    gitea_image: docker.gitea.com/gitea:1.26.4

    # Dockhand facts
    # renovate: datasource=docker depName=fnsys/dockhand
    dockhand_image: fnsys/dockhand:v1.0.35

    # Semaphore facts
    # renovate: datasource=docker depName=semaphoreui/semaphore
    semaphore_image: semaphoreui/semaphore:v2.18.12
    semaphore_deploy_docker_volume_backup: true

    # Termix facts
    # renovate: datasource=docker depName=ghcr.io/lukegus/termix
    termix_image: ghcr.io/lukegus/termix:2.4.1
    termix_deploy_docker_volume_backup: true

    # IT-Tools facts
    # renovate: datasource=docker depName=corentinth/it-tools
    it_tools_image: corentinth/it-tools:2024.10.22-7ca5933

    # Networking Toolbox facts
    # renovate: datasource=docker depName=lissy93/networking-toolbox
    networking_toolbox_image: lissy93/networking-toolbox:1.6.0

    # TODO
    #
    # Add:
    # HomeLabInfo
    # Homelable

  pre_tasks:
    - name: Print hostvars
      when: false
      ansible.builtin.debug:
        var: hostvars['lxc-controller']

    - name: Ensure base environment is configured
      when: true
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

    # Load environment variables applicable to the homelab environment
    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Print hostvars
      when: false
      ansible.builtin.debug:
        var: hostvars['lxc-controller']

  tasks:
    - name: Deploy a containerised instance of Tinyauth
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-tinyauth.yaml

    - name: Deploy a containerised instance of Dockhand
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-dockhand.yaml

    - name: Deploy a containerised instance of Termix
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-termix.yaml

    - name: Deploy a containerised instance of Semaphore
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-semaphore.yaml

    - name: Deploy a containerised instance of IT-Tools
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-it_tools.yaml

    - name: Deploy a containerised instance of Networking Toolbox
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-networking-toolbox.yaml
