---

- name: Deploy Grist

  hosts: productivity

  vars:

    # Grist facts
    # renovate: datasource=docker depName=gristlabs/grist
    grist_image: gristlabs/grist:1.7.12

    grist_deploy_docker_volume_backup: true

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Grist
      ansible.builtin.include_tasks:
        file: tasks/deploy-grist.yaml
