---
- name: Deploy Uptime Kuma

  hosts: uptimekuma

  vars:

    # Uptime Kuma facts
    uptimekuma_image_name: louislam/uptime-kuma
    uptimekuma_image_tag: 1.23.16-alpine
    uptimekuma_service_name: uptimekuma
    uptimekuma_service_port: 3001
    uptimekuma_volume_name: uptimekuma

  tasks:

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Uptime Kuma
      ansible.builtin.include_tasks:
        file: tasks/deploy-uptimekuma.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_volume_to_backup:
          - "{{ uptimekuma_volume_name }}:/backup/uptimekuma-backup:ro"
