---
- name: Deploy Monitor stack

  hosts: monitor

  vars:
    # Uptime Kuma facts
    # renovate: datasource=docker depName=louislam/uptime-kuma
    uptimekuma_image: louislam/uptime-kuma:2.3.2-slim
    uptimekuma_deploy_docker_volume_backup: true

    # What's up Docker? facts
    # renovate: datasource=docker depName=getwud/wud
    wud_image: getwud/wud:8.2.2

    # Pulse facts
    # renovate: datasource=docker depName=rcourtman/pulse
    pulse_image: rcourtman/pulse:v5.1.34

  pre_tasks:
    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:

    - name: Deploy a containerised instance of Uptime Kuma
      ansible.builtin.include_tasks:
        file: tasks/deploy-uptimekuma.yaml

    - name: Deploy a containerised instance of What's up Docker?
      ansible.builtin.include_tasks:
        file: tasks/deploy-wud.yaml

    - name: Deploy a containerised instance of Pulse
      ansible.builtin.include_tasks:
        file: tasks/deploy-pulse.yaml
