---
- name: Deploy AI stack

  hosts: ai

  vars:
    # Assumes Ollama is already deployed
    # ollama_base_url: "{{ ollama_base_url | default('http://lxc-ollama-cpu.localdomain:11434') }}"

    # SearXNG facts
    searxng_homepage_hide: true

    # Open WebUI facts
    # renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
    open_webui_image: ghcr.io/open-webui/open-webui:0.9.6-slim
    open_webui_network_name: open-webui

    # n8n facts
    # renovate: datasource=docker depName=docker.n8n.io/n8nio/n8n
    n8n_image: n8nio/n8n:2.26.2

    # mcpo facts
    # renovate: datasource=docker depName=ghcr.io/open-webui/mcpo
    mcpo_image: ghcr.io/open-webui/mcpo:main

    # ha-mcp facts
    # renovate: datasource=docker depName=ghcr.io/homeassistant-ai/ha-mcp
    ha_mcp_image: ghcr.io/homeassistant-ai/ha-mcp:7.7.0

    # affine-mcp-server facts
    # renovate: datasource=docker depName=ghcr.io/dawncr0w/affine-mcp-server
    affine_mcp_server_image: ghcr.io/dawncr0w/affine-mcp-server:latest

  pre_tasks:
    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

  tasks:
    - name: Deploy a containerised instance of SearXNG
      ansible.builtin.include_tasks:
        file: tasks/deploy-searxng.yaml
      vars:
        searxng_network_name: "{{ open_webui_network_name }}"

    # Open WebUI is configured to use Ollama as its backend LLM provider
    # and SearXNG as its search engine provider.
    # Expects Ollama and SearXNG to be running on the same network.
    - name: Deploy a containerised instance of Open WebUI
      ansible.builtin.include_tasks:
        file: tasks/deploy-open-webui.yaml

    - name: Deploy a containerised instance of n8n
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-n8n.yaml

    # Deplpy MCP Servers
    #
    - name: Deploy a containerised instance of mcpo
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-mcpo.yaml

    - name: Deploy a containerised instance of Home Assistant MCP
      when: true
      ansible.builtin.include_tasks:
        file: tasks/deploy-ha-mcp.yaml

    - name: Deploy a containerised instance of affine-mcp-server
      when: false
      ansible.builtin.include_tasks:
        file: tasks/deploy-affine-mcp-server.yaml
