---
- name: Configure base hosts os

  hosts: all

  vars:

    base_os_packages:
      - rsync

  tasks:

    - name: Update and upgrade hosts using apt
      ansible.builtin.include_tasks:
        file: tasks/homelab-configure-base-os.yaml
