---
- name: Install and configure Docker and base containers

  hosts: whatsupdocker # homelab_lxc_docker

  vars:

    base_os_packages:
      - rsync

    # Base containerised service details
    # Docker Socket Proxy service facts
    docker_socket_proxy_image: ghcr.io/tecnativa/docker-socket-proxy:edge
    docker_socket_proxy_service_name: docker-socket-proxy
    docker_socket_proxy_service_port: 2375
    # Node Exporter service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Portainer Agent service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Prometheus service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Traefik service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Watchtower service facts
    watchtower_image: containrrr/watchtower:1.7.1
    watchtower_service_name: watchtower
    watchtower_service_port: 8080

  tasks:

    - name: Configure base OS
      ansible.builtin.include_tasks:
        file: tasks/homelab-deploy-support-services.yaml
