---
- name: Install and configure Docker and base containers

  hosts: whatsupdocker # homelab_lxc_docker

  vars:

    base_os_packages:
      - rsync

  tasks:

    - name: Configure base OS
      ansible.builtin.include_tasks:
        file: tasks/homelab-deploy-support-services.yaml
