---
- name: Install and configure Docker and base containers

  hosts: homelab_lxc_docker

  vars:

    base_os_packages:
      - rsync

  tasks:

    - name: Configure base containerised services
      ansible.builtin.include_tasks:
        file: tasks/homelab-deploy-support-services.yaml
      tags: always
