---
- name: Deploy Homelab Controller Node

  hosts: lxc-controller

  vars:

    # Dockhand facts
    # renovate: datasource=docker depName=fnsys/dockhand
    dockhand_image: fnsys/dockhand:v1.0.18

    # Semaphore facts
    # renovate: datasource=docker depName=semaphoreui/semaphore
    semaphore_image: semaphoreui/semaphore:v2.17.36
    semaphore_deploy_docker_volume_backup: false

  pre_tasks:

    - name: Ensure base environment is configured
      ansible.builtin.include_tasks:
        file: tasks/configure-containerised-base.yaml

  tasks:

    # Load environment variables applicable to the homelab environment
    - name: homelab-deploy-support-services | Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Deploy a containerised instance of Dockhand
      ansible.builtin.include_tasks:
        file: tasks/deploy-dockhand.yaml

    - name: Deploy a containerised instance of Semaphore
      ansible.builtin.include_tasks:
        file: tasks/deploy-semaphore.yaml

    - name: Deploy a containerised instance of Docker Volume Backup
      when: semaphore_deploy_docker_volume_backup | default(false)
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-volume-backup.yaml
      vars:
        docker_volume_backup_service_name: "docker-volume-backup-{{ semaphore_service_name }}"
        docker_volume_backup_volume_to_backup:
          - "{{ semaphore_volume_data_name }}:/backup/{{ semaphore_service_name }}-backup:ro"
        docker_volume_backup_backup_label: "{{ semaphore_service_name }}"
        docker_volume_backup_backup_retention_days: 3
