---
- name: Configure hosts

  hosts: all

  tasks:

    - name: Get hostname of LXC
      ansible.builtin.command: hostname
      register: lxc_hostname

    - name: Output hostname
      ansible.builtin.debug:
        msg: "Running on container {{ lxc_hostname.stdout }}"

    - name: Set timezone to Australia/Adelaide
      community.general.timezone:
        name: Australia/Adelaide

    - name: Update all packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe

    - name: Install rsync (required to synchronise files)
      ansible.builtin.package:
        name: rsync
        state: present

    # FIXME: Hack as delegate_to does not provide expected ansible_hostname
    - name: Get name of host tasks are being run on
      ansible.builtin.shell:
        cmd: hostname
      register: command_output

    - name: Set remote hostname
      ansible.builtin.set_fact:
        remote_hostname: "{{ command_output.stdout }}"
