---
- name: Install and configure Docker and base containers

  hosts: homelab_lxc_docker

  vars:

    # Base containerised service details
    # Docker Socket Proxy service facts
    docker_socket_proxy_image: ghcr.io/tecnativa/docker-socket-proxy:edge
    docker_socket_proxy_service_name: docker-socket-proxy
    docker_socket_proxy_service_port: 2375
    # Node Exporter service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Portainer Agent service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Prometheus service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Traefik service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Watchtower service facts
    watchtower_image: containrrr/watchtower:1.7.1
    watchtower_service_name: watchtower
    watchtower_service_port: 8080

  tasks:

    - name: Check Docker is available  # noqa: syntax-check[unknown-module]
      community.docker.docker_host_info:
      register: host_docker_info
      ignore_errors: true

    # - name: Install Docker
    #   when:  host_docker_info.rc != 0
    #   ansible.builtin.import_role:
    #     name: geerlingguy.docker
    #   vars:
    #     docker_install_compose: false
    #     docker_users:
    #       - root

    # - name: Set Docker network facts
    #   ansible.builtin.set_fact:
    #     docker_socket_proxy_network:
    #       name: "{{ docker_socket_proxy_network_name | default('docker-socket-proxy') }}"
    #       driver: bridge
    #       internal: true
    #     monitoring_network:
    #       name: "{{ monitoring_network_name | default('monitoring') }}"
    #       driver: bridge
    #       internal: true
    #     web_network:
    #       name: "{{ web_network_name | default('web') }}"
    #       driver: bridge
    #       internal: false

    # - name: debug
    #   ansible.builtin.debug:
    #     var: docker_socket_proxy_network

    # - name: debug
    #   ansible.builtin.debug:
    #     var: docker_socket_proxy_network.name

    - name: Load homelab vars
      ansible.builtin.include_vars:
        file: vars/homelab_env.yaml

    - name: Create Docker networks  # noqa: syntax-check[unknown-module]
      community.docker.docker_network:
        name: "{{ item.name }}"
        driver: "{{ item.driver }}"
        internal: "{{ item.internal }}"
      loop:
        - name: "{{ docker_socket_proxy_network_name | default('docker-socket-proxy') }}"
          driver: bridge
          internal: true
        - name: "{{ monitoring_network_name | default('monitoring') }}"
          driver: bridge
          internal: true
        - name: "{{ web_network_name | default('web') }}"
          driver: bridge
          internal: false

    - name: Deploy a containerised instance of Docker Socket Proxy
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-socket-proxy.yaml

    - name: Deploy a containerised instance of Portainer Agent
      ansible.builtin.include_tasks:
        file: tasks/deploy-portainer-agent.yaml

    - name: Deploy a containerised instance of Traefik
      ansible.builtin.include_tasks:
        file: tasks/deploy-traefik.yaml

    - name: Deploy a containerised instance of Node Exporter
      ansible.builtin.include_tasks:
        file: tasks/deploy-node-exporter.yaml

    - name: Deploy a containerised instance of Prometheus
      ansible.builtin.include_tasks:
        file: tasks/deploy-prometheus.yaml
