---
- name: Install and configure Docker and base containers

  hosts: all

  vars:

    # Base containerised service details
    # Docker Socket Proxy service facts
    docker_socket_proxy_image_name: ghcr.io/tecnativa/docker-socket-proxy
    docker_socket_proxy_image_tag: edge
    docker_socket_proxy_service_name: "docker-socket-proxy"
    docker_socket_proxy_service_port: 2375
    # Node Exporter service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Portainer Agent service facts
    portainer_agent_image_name: portainer/agent
    portainer_agent_image_tag: 2.26.1-alpine
    portainer_agent_service_name: portainer_agent
    portainer_agent_service_port: 9001
    # Prometheus service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Traefik service facts
    # Defined in playbooks/group_vars/homelab_lxc
    # Watchtower service facts
    watchtower_image_name: containrrr/watchtower
    watchtower_image_tag: 1.7.1
    watchtower_service_name: watchtower
    watchtower_service_port: 8080

  tasks:

    - name: Install and configure Docker base
      tags:
        - always

      block:
        # - name: Install Docker
        #   ansible.builtin.import_role:
        #     name: geerlingguy.docker
        #   vars:
        #     docker_install_compose: false
        #     docker_users:
        #       - root

        ####### DOCKER NETWORK SECTION

        # - name: Set Docker Network facts
        #   ansible.builtin.set_fact:
        #     docker_socket_proxy_network_name: "{{ docker_socket_proxy_network_name | default('docker-socket-proxy') }}"
        #     monitoring_network_name: "{{ monitoring_network_name | default('monitoring') }}"
        #     web_network_name: "{{ web_network_name | default('web') }}"

        # Based on https://github.com/wollomatic/traefik2-hardened/blob/master/docker-compose.yaml
        - name: Create a Docker Socket Proxy Docker network  # noqa: syntax-check[unknown-module]
          community.docker.docker_network:
            name: "{{ docker_socket_proxy_network_name | default('docker-socket-proxy') }}"
            driver: bridge
            internal: true

        - name: Create a Monitoring Docker Network
          community.docker.docker_network:
            name: "{{ monitoring_network_name | default('monitoring') }}"
            internal: true

        - name: Create a Web Docker Network
          community.docker.docker_network:
            name: "{{ web_network_name | default('web') }}"
            internal: false

    - name: Deploy a containerised instance of Docker Socket Proxy
      ansible.builtin.include_tasks:
        file: tasks/deploy-docker-socket-proxy.yaml

    - name: Deploy a containerised instance of Portainer Agent
      ansible.builtin.include_tasks:
        file: tasks/deploy-portainer-agent.yaml

    - name: Deploy a containerised instance of Traefik
      ansible.builtin.include_tasks:
        file: tasks/deploy-traefik.yaml

    - name: Deploy a containerised instance of Node Exporter
      ansible.builtin.include_tasks:
        file: tasks/deploy-node-exporter.yaml

    - name: Deploy a containerised instance of Prometheus
      ansible.builtin.include_tasks:
        file: tasks/deploy-prometheus.yaml
